'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {api} from '@/lib/api';
import {replayMutation} from '@/lib/replay';
type Entry={id:string;version:number;kind:string;label:string;payload:Record<string,unknown>};
type Draft={id:string;state:string;validation:{field:string;code:string}[]};
type Version={version:number;payload:Record<string,unknown>;change?:{actor_id:string;reason:string;at:string}|null};
const areas=[{value:'all',label:'All settings',hint:'Choose any permitted rule or record.'},{value:'expense_policies',label:'Allowances & receipts',hint:'Amounts, eligible units and receipt requirements.'},{value:'approval_policies',label:'Approval hierarchy',hint:'Amount bands and required authorities.'},{value:'people',label:'People & teams',hint:'Employees, departments and cost centres.'},{value:'vendors',label:'Vendors',hint:'Approved suppliers and their effective dates.'},{value:'budgets',label:'Budgets',hint:'Audited adjustments to available capacity.'},{value:'authority',label:'Delegation & exceptions',hint:'Delegated authority and waiver rules.'}];
const belongs=(entry:Entry,group:string)=>group==='all'||entry.kind===group||group==='people'&&['employees','cost_centers'].includes(entry.kind)||group==='authority'&&['delegations','waiver_policies'].includes(entry.kind);
const readable=(value:unknown)=>String(value??'Not configured').toLowerCase().replaceAll('_',' ').replace(/^./,s=>s.toUpperCase());
const names:Record<string,string>={expense_policies:'Allowance',approval_policies:'Approval policy',vendors:'Vendor',employees:'Employee',cost_centers:'Cost centre',delegations:'Delegated authority',waiver_policies:'Waiver policy',budgets:'Budget'};
const fields:Record<string,string[]>={expense_policies:['allowance_amount','effective_from','effective_to','submission_window_days','receipt_required'],vendors:['legal_name','status','effective_from','effective_to'],employees:['name','department','status','effective_from','effective_to'],cost_centers:['name','department'],delegations:['ceiling_amount','effective_from','effective_to'],waiver_policies:['maximum_days','effective_from','effective_to'],approval_policies:['effective_from','effective_to']};
const labels:Record<string,string>={allowance_amount:'New allowance',effective_from:'Effective from',effective_to:'Effective until (exclusive)',submission_window_days:'Submission window (days)',receipt_required:'Receipt required',legal_name:'Legal name',name:'Name',department:'Department',status:'Status',ceiling_amount:'Authority ceiling',maximum_days:'Maximum waiver duration (days)'};
export function AdminConsole({roles}:{roles:string[]}){
 const [items,setItems]=useState<Entry[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[values,setValues]=useState<Record<string,string>>({}),[reason,setReason]=useState(''),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[history,setHistory]=useState<Version[]>([]),[loaded,setLoaded]=useState(false),[group,setGroup]=useState('all');
 const [activating,setActivating]=useState(false);
 const [bands,setBands]=useState<{from_amount:string;to_amount:string|null;roles:string[]}[]>([]);
 const config=roles.some(r=>['POLICY_ADMIN','REFERENCE_ADMIN','LEDGER_ADMIN'].includes(r));
 async function load(){if(config){const c=await api<{items:Entry[]}>('admin/catalog');setItems(c.items);setLoaded(true);}}
 useEffect(()=>{void load().catch(e=>{setError(e.message);setLoaded(true)})},[config]);
 const entry=items.find(r=>r.id===selected);
 const snapshot=JSON.stringify([entry?.id,entry?.version,values,reason,bands]);const current=useRef(snapshot);current.current=snapshot;
 useEffect(()=>{let active=true;setDraft(null);setHistory([]);setReason('');setError('');if(entry){setValues(Object.fromEntries(Object.entries(entry.payload).filter(([,v])=>typeof v==='string'||typeof v==='number'||typeof v==='boolean').map(([k,v])=>[k,String(v)])));void api<{items:Version[]}>('admin/records/'+entry.id+'/versions').then(r=>{if(active)setHistory(r.items)}).catch(e=>{if(active)setError(e.message)});setBands((entry.payload.bands as {lower_bound_amount:string;upper_bound_amount:string|null;required_roles:string[]}[]||[]).map(b=>({from_amount:b.lower_bound_amount,to_amount:b.upper_bound_amount,roles:b.required_roles})));}return()=>{active=false}},[selected,entry?.version]);
 useEffect(()=>{setDraft(null)},[values,reason,bands]);
 async function save(e:React.FormEvent){e.preventDefault();if(!entry)return;setBusy(true);setError('');setNotice('');try{
  const changes:Record<string,unknown>={expected_version:entry.version,reason};
  for(const k of fields[entry.kind]||[]){if(values[k]!==String(entry.payload[k]??''))changes[k]=k==='receipt_required'?values[k]==='true':['submission_window_days','maximum_days'].includes(k)?Number(values[k]):values[k];}
  if(entry.kind==='approval_policies')changes.bands=bands;
  const result=await replayMutation<Draft>('admin/records/'+entry.id+'/drafts',changes);
  if(current.current===snapshot)setDraft(result);else setNotice('The form changed while validation was running. Validate the current values before activation.');
 }catch(e){if(current.current===snapshot)setError((e as Error).message)}finally{setBusy(false)}}
 async function activate(){if(!draft||busy)return;setBusy(true);setActivating(true);setError('');try{setDraft(await replayMutation<Draft>('admin/drafts/'+draft.id+'/activate',{reason}));await load();setNotice('New configuration version activated. Earlier versions and evaluations remain available.');}catch(e){setError((e as Error).message)}finally{setBusy(false);setActivating(false)}}
 const versionRow=(h:Version)=><li key={h.version}><strong>Version {h.version} · effective {String(h.payload.effective_from||'Not dated')} to {String(h.payload.effective_to||'Not dated')}</strong><p>{String(h.payload.currency||'')} {String(h.payload.allowance_amount||h.payload.legal_name||h.payload.name||'Retained configuration')}</p>{h.change?<small>{h.change.reason} · {new Date(h.change.at).toLocaleString()}</small>:<small>Original imported version</small>}</li>;
 return <><div className="page-title"><div><h1>Business configuration</h1><p>Keep the rules clear. Keep every change traceable.</p></div></div>
 <div className="admin-service-links">{roles.includes('REFERENCE_ADMIN')?<Link href="/reference-imports"><strong>Reference data</strong><span>Validate and import approved records</span></Link>:null}{roles.some(r=>['OPERATIONS_ADMIN','SYSTEM_ADMIN'].includes(r))?<Link href="/operations"><strong>Health & recovery</strong><span>Service status, jobs and operational audit</span></Link>:null}{roles.some(r=>['ML_ADMIN','ML_GOVERNANCE'].includes(r))?<Link href="/intelligence"><strong>Intelligence governance</strong><span>Governed feedback, datasets and lifecycle</span></Link>:null}</div>
 {error?<p className="error" role="alert">{error}</p>:null}{notice?<p className="notice" role="status">{notice}</p>:null}
 {config?<><div className="admin-tabs" aria-label="Configuration areas">{areas.map(a=><button className="secondary" key={a.value} disabled={activating} aria-pressed={group===a.value} onClick={()=>{setNotice('');setGroup(a.value);setSelected('')}}>{a.label}</button>)}</div>
 <section className="panel admin-editor"><div className="section-title"><div><h2>{entry?readable(entry.payload.category||entry.payload.name||entry.payload.legal_name||names[entry.kind]):'Choose the rule or record'}</h2><p className="hint">{areas.find(a=>a.value===group)?.hint}</p></div></div>
 {!loaded?<p role="status">Loading business configuration…</p>:!items.length?<p className="notice">No business configuration exists for this scope. An authorized administrator must import approved policies and references; missing policies cannot permit processing.</p>:null}
 <label>Configuration record<select disabled={activating} value={selected} onChange={e=>{setNotice('');setSelected(e.target.value)}}><option value="">Choose a setting</option>{items.filter(r=>belongs(r,group)).map(r=><option key={r.id} value={r.id}>{names[r.kind]||readable(r.kind)} · {readable(r.payload.category||r.payload.name||r.payload.legal_name||r.label)} · version {r.version}</option>)}</select></label>
 {entry?<><p className="fixture-notice">{entry.payload.synthetic===true||/DEMO|SYNTHETIC/i.test(String(entry.payload.label||entry.label))||String(entry.payload.source_system||'').includes('SYNTHETIC')?'Fictional sample configuration. Replace it with business-approved policy before live use.':'Business-configured record. Effective dates and versions govern applicability.'}</p>
 <div className="policy-context"><h3>What this rule covers</h3><dl><div><dt>Current version</dt><dd>{entry.version}</dd></div>{entry.kind==='expense_policies'?<><div><dt>Current allowance</dt><dd>{String(entry.payload.currency)} {String(entry.payload.allowance_amount)}</dd></div><div><dt>Allowance unit</dt><dd>{readable(entry.payload.unit)}</dd></div>{Object.entries(entry.payload.dimensions as Record<string,unknown>||{}).map(([key,value])=><div key={key}><dt>{readable(key)}</dt><dd>{String(value)}</dd></div>)}</>:null}</dl><p className="hint">Scope, currency and unit come from the selected business record. Changing the amount does not change whom it covers.</p></div>
 {entry.kind==='budgets'?<BudgetForm key={entry.id} entry={entry}/>:<form onSubmit={save} className="policy-form"><fieldset className="policy-inputs" disabled={activating}><h3>Set the change</h3><div className="form-grid">{(fields[entry.kind]||[]).map(k=><label key={k}>{labels[k]}{k==='receipt_required'?<select value={values[k]||'false'} onChange={e=>setValues(v=>({...v,[k]:e.target.value}))}><option value="true">Yes</option><option value="false">No</option></select>:k==='status'?<select value={values[k]||''} onChange={e=>setValues(v=>({...v,[k]:e.target.value}))}>{(entry.kind==='vendors'?['APPROVED','BLOCKED','INACTIVE']:['ACTIVE','INACTIVE']).map(v=><option key={v}>{v}</option>)}</select>:<input type={k.startsWith('effective_')?'date':'text'} inputMode={k.endsWith('amount')?'decimal':undefined} value={values[k]||''} onChange={e=>setValues(v=>({...v,[k]:e.target.value}))} required/>}</label>)}</div>
 {entry.kind==='approval_policies'?bands.map((b,i)=><fieldset key={i}><legend>Approval band {i+1}</legend><label>From amount<input value={b.from_amount} onChange={e=>setBands(v=>v.map((x,n)=>n===i?{...x,from_amount:e.target.value}:x))}/></label><label>Until amount (blank for no ceiling)<input value={b.to_amount||''} onChange={e=>setBands(v=>v.map((x,n)=>n===i?{...x,to_amount:e.target.value||null}:x))}/></label><label>Required authority (comma separated roles)<input value={b.roles.join(', ')} onChange={e=>setBands(v=>v.map((x,n)=>n===i?{...x,roles:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)}:x))}/></label></fieldset>):null}
 <label>Configuration change reason<input value={reason} onChange={e=>setReason(e.target.value)} minLength={3} required placeholder="Explain why this change is needed"/></label><p className="hint">Validate first. Activation creates a new version and records your reason and identity.</p><button disabled={busy}>{busy?'Validating…':'Validate and save draft'}</button></fieldset></form>}
 {draft?<section className="change-preview" aria-label="Validated change"><h3>Review the policy change</h3><p role="status">Draft {draft.state.toLowerCase()}</p>{entry.kind==='expense_policies'?<dl><div><dt>Allowance</dt><dd>{String(entry.payload.currency)} {String(entry.payload.allowance_amount)} → {values.allowance_amount} per {String(entry.payload.unit).toLowerCase().replaceAll('_',' ')}</dd></div><div><dt>Effective period</dt><dd>{values.effective_from} to {values.effective_to} (exclusive)</dd></div><div><dt>New version</dt><dd>{entry.version+1}</dd></div><div><dt>Reason</dt><dd>{reason}</dd></div></dl>:<p>New version {entry.version+1}. Reason: {reason}</p>}{draft.validation.length?<div role="alert">{draft.validation.map((v,i)=><p key={i}>{labels[v.field]||readable(v.field)}: {readable(v.code)}. Correct the value and validate again.</p>)}</div>:null}<button disabled={busy||draft.state!=='VALID'} onClick={activate}>Activate new version</button></section>:null}
 <details className="policy-history"><summary>Policy versions and audit metadata</summary><ol className="version-list">{history.slice(-3).reverse().map(versionRow)}</ol>{history.length>3?<details><summary>Earlier versions ({history.length-3})</summary><ol className="version-list">{history.slice(0,-3).reverse().map(versionRow)}</ol></details>:null}<details><summary>Full audit record and identifiers</summary><pre>{JSON.stringify(history,null,2)}</pre></details></details>
 </>:<div className="empty"><h3>Pick a setting to get started.</h3><p>Choose a category, then a record. You’ll see its scope before making a change.</p></div>}</section></>:<p className="panel">Choose an administration area permitted for your role.</p>}</>;
}
function BudgetForm({entry}:{entry:Entry}){
 const [amount,setAmount]=useState(''),[direction,setDirection]=useState('INCREASE'),[reason,setReason]=useState(''),[error,setError]=useState(''),[done,setDone]=useState(false),[busy,setBusy]=useState(false);
 const submitting=useRef(false);
 return <form className="policy-form" onSubmit={async e=>{e.preventDefault();if(submitting.current)return;submitting.current=true;setError('');setDone(false);setBusy(true);try{await replayMutation('budgets/'+entry.id+'/adjustments',{amount,direction,reason},true);setDone(true);setAmount('');setReason('')}catch(e){setError((e as Error).message)}finally{setBusy(false);submitting.current=false}}}><h3>Adjust the budget</h3><p>Adjustments append ledger events; active reservations and history remain protected.</p><label>Budget adjustment amount<input inputMode="decimal" value={amount} disabled={busy} onChange={e=>{setDone(false);setAmount(e.target.value)}} required/></label><label>Adjustment direction<select value={direction} disabled={busy} onChange={e=>setDirection(e.target.value)}><option>INCREASE</option><option>DECREASE</option></select></label><label>Budget adjustment reason<input value={reason} disabled={busy} onChange={e=>{setDone(false);setReason(e.target.value)}} minLength={3} required/></label><button disabled={busy||!amount||reason.trim().length<3}>Add audited adjustment</button>{error?<p role="alert" className="error">{error}</p>:null}{done?<p role="status">Budget adjustment recorded.</p>:null}</form>;
}
