'use client';
import Link from 'next/link';
import {BusinessFacts} from './business-facts';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {fieldLabel,processingLabel,observationLabel} from '@/lib/presentation';
import {api,mutate,type Canonical} from '@/lib/api';
import {replayMutation} from '@/lib/replay';

type Box={x1:number;y1:number;x2:number;y2:number};
type Source={page:number|null;bbox:Box|null;document_id:string};
type Observation={id:string;field_path:string;state:string;raw_value:string|null;source:Source|null;diagnostic:string|null};
type Document={id:string;generation:number;intake_hint:string;display_name:string;source_type:string;state:string;last_error:string|null;segmentation_state:string;
 pages:{page:number;page_sha256?:string;preview_url:string;transform:{exif_orientation?:number};route:string;quality:Record<string,number>}[];
 observations:Observation[];draft:{id:string;candidate:Record<string,string|null>;findings:{field:string;code:string;message?:string}[];traces:{field_path:string;status:string;steps:string[]}[]}|null;
 original:{sha256:string;byte_size:number;detected_mime:string}|null;
 jobs:{stage:string;state:string;attempts:number;metadata:unknown}[];
 extraction_runs:{adapter:string;metadata:unknown;status:string}[]};
export type DocumentDetail=Document;
type DocList={id:string;display_name:string;source_type:string;state:string;last_error:string|null};
export type DocumentEvidence={document:Document;reference:Source;source_image_available:boolean};
const working=new Set(['QUEUED','PROCESSING','FAILED_RETRYABLE']);

export function processingError(code:string|null):string|null {
 if(!code)return null;
 if(code==='DOCUMENT_TYPE_UNCONFIRMED')return 'Choose Vendor invoice or Employee expense to continue. The document does not provide a clear type; no finance decision has been made.';
 if(['PROVIDER_UNAVAILABLE','VISUAL_PROVIDER_NOT_CONFIGURED','PROVIDER_AUTH_NOT_CONFIGURED','PROVIDER_MODEL_UNAVAILABLE'].includes(code))return 'Visual extraction service is unavailable. Start the local inference service or ask an operational administrator to restore it, then retry the document.';
 if(['PROVIDER_TIMEOUT','PROVIDER_CALL_BUDGET','PROVIDER_ROW_LIMIT','OCR_DOCUMENT_TIME_LIMIT'].includes(code))return 'Document extraction reached its configured processing limit. Ask an operational administrator to inspect the failure; simplify or confirm the document pages before retrying.';
 return code.replaceAll('_',' ').toLowerCase();
}

function derivedBox(box:Box,orientation:number):Box {
 const point=(u:number,v:number):number[]=>({1:[u,v],2:[1-u,v],3:[1-u,1-v],4:[u,1-v],5:[v,u],6:[1-v,u],7:[1-v,1-u],8:[v,1-u]}[orientation]||[u,v]);
 const points=[point(box.x1,box.y1),point(box.x1,box.y2),point(box.x2,box.y1),point(box.x2,box.y2)];
 return {x1:Math.min(...points.map(p=>p[0])),y1:Math.min(...points.map(p=>p[1])),x2:Math.max(...points.map(p=>p[0])),y2:Math.max(...points.map(p=>p[1]))};
}

export function SourceViewer({document,source}:{document:Document;source?:Source|null}) {
 const [page,setPage]=useState(source?.page||1);
 const [zoom,setZoom]=useState(100);
 useEffect(()=>{if(source?.page)setPage(source.page)},[source]);
 const p=document.pages.find(p=>p.page===page);const bbox=source?.page===page&&source.bbox?derivedBox(source.bbox,p?.transform.exif_orientation||1):null;
 return <section className="panel source-viewer" aria-label="Document source viewer"><div className="section-title"><h2>Original source page</h2><label>Source page<select value={page} onChange={e=>setPage(Number(e.target.value))}>{document.pages.map(p=><option key={p.page} value={p.page}>Page {p.page}</option>)}</select></label></div>
 {p?<><label className="source-zoom">Preview zoom<select aria-label="Preview zoom" value={zoom} onChange={e=>setZoom(Number(e.target.value))}>{[100,150,200,300].map(value=><option key={value} value={value}>{value}%</option>)}</select></label><div className="source-scroll" tabIndex={0} aria-label="Scrollable source preview"><div className="page-preview" style={{width:`${zoom}%`}}><img src={p.preview_url.replace('/api/v1/','/api/')} alt={`${document.display_name}, page ${page}`} />{bbox?<span className="source-box" aria-label="Actual source bounding box" style={{left:`${bbox.x1*100}%`,top:`${bbox.y1*100}%`,width:`${(bbox.x2-bbox.x1)*100}%`,height:`${(bbox.y2-bbox.y1)*100}%`}}/>:null}</div></div><p className="hint">{bbox?'Highlighted measured text region.':'Page-level evidence. No field box is available.'} The preserved original is unchanged.</p></>:<p className="empty">No safely rendered page available.</p>}
 {document.original&&document.pages.length&&document.state!=='QUARANTINED'?<a href={`/api/documents/${document.id}/original`} download>Download preserved original</a>:null}</section>
}

export function Documents({id}:{id?:string}) {
 const router=useRouter();const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);const [items,setItems]=useState<DocList[]|null>(null),[document,setDocument]=useState<Document|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [files,setFiles]=useState<File[]>([]),[kind,setKind]=useState('AUTO'),[source,setSource]=useState<Source|null>(null);
 const [intake,setIntake]=useState<{malware_required:boolean;malware_scanner:string;maximum_bytes:number;maximum_pages:number}|null>(null);
 useEffect(()=>{void api<{malware_required:boolean;malware_scanner:string;maximum_bytes:number;maximum_pages:number}>('documents/intake-capabilities').then(setIntake).catch(()=>setIntake(null))},[]);
 const [edits,setEdits]=useState<Record<string,{value:string;page:number}>>({}),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[canonical,setCanonical]=useState(''),[existing,setExisting]=useState(''),[version,setVersion]=useState(1);
 useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;
  async function load(){try{if(id){const d=await api<Document>('documents/'+id);if(active){setDocument(d);if(working.has(d.state))timer=setTimeout(load,900)}}else{const r=await api<{items:DocList[]}>('documents');if(active)setItems(r.items)}}catch(e){if(active)setError((e as Error).message)}}
  void load();return()=>{active=false;clearTimeout(timer)};
 },[id]);
 useEffect(()=>{if(!document?.draft)return;let active=true;const branch=document.source_type==='EMPLOYEE_RECEIPT'?'employee':'vendor';
  const caseId=new URLSearchParams(window.location.search).get('case');
  if(caseId){void api<{version:number;versions:{payload:Canonical}[]}>('transactions/'+caseId).then(record=>{
   if(active){setExisting(caseId);setVersion(record.version);setCanonical(JSON.stringify(record.versions.at(-1)!.payload,null,2));}
  }).catch(e=>{if(active)setError((e as Error).message)});return()=>{active=false};}
  api<{development:boolean}>('me').then(me=>me.development?api<Canonical>('development/templates/'+branch):Promise.resolve({document_type:'ORDINARY',branch:branch==='vendor'?'VENDOR_INVOICE':'EMPLOYEE_EXPENSE',lines:[],items:[]} as Canonical)).then(template=>{
   const candidate=document.draft!.candidate;const p={...template};
   if(branch==='vendor'){for(const k of ['invoice_number','invoice_date','currency','total_amount','subtotal_amount','tax_amount','document_discount_amount','shipping_amount','other_charges_amount','tax_basis','payment_account_token'] as const){(p as Record<string,unknown>)[k]=candidate[k]??null}p.source_document_id=document.id;
    const indices=[...new Set(Object.keys(candidate).filter(k=>k.startsWith('lines.')).map(k=>k.split('.')[1]))];p.lines=indices.map((i,n)=>{const line={...template.lines?.[Math.min(n,(template.lines?.length||1)-1)]};delete line.id;return {...line,...Object.fromEntries(['quantity','unit_price','discount_amount','net_amount','tax_rate','tax_amount','gross_amount','uom'].map(k=>[k,candidate[`lines.${i}.${k}`]??null])),currency:candidate.currency}});
   }else{p.expense_date=candidate.expense_date;p.currency=candidate.currency;p.requested_amount=candidate.total_amount;p.items=[{...template.items?.[0],source_document_id:document.id,expense_date:candidate.expense_date,currency:candidate.currency,category:candidate.category,local_timezone:candidate.local_timezone,receipt_total_amount:candidate.total_amount,claimed_amount:candidate.total_amount,eligible_nights:null}];}
   if(active)setCanonical(JSON.stringify(p,null,2));
  }).catch(e=>{if(active)setError((e as Error).message)});return()=>{active=false};
 },[document?.draft?.id]);
 async function upload(){setBusy(true);setError('');try{
  if(intake&&files.some(file=>file.size>intake.maximum_bytes))throw new Error(`Document exceeds the configured ${intake.maximum_bytes} byte limit.`);
  let last='';for(const file of files){const key=crypto.randomUUID();const mime=file.type||(/\.pdf$/i.test(file.name)?'application/pdf':/\.png$/i.test(file.name)?'image/png':'image/jpeg');
   const s=await mutate<{id:string;document_id:string;bytes_url:string;maximum_bytes:number}>('uploads',{filename:file.name,mime,source_type:kind},key);
   if(file.size>s.maximum_bytes)throw new Error(`Document exceeds the configured ${s.maximum_bytes} byte limit.`);
   const stored=await api<{error?:string}>(s.bytes_url.replace('/api/v1/',''),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});
   if(stored.error)throw new Error(stored.error);
   await mutate('uploads/'+s.id+'/finalize',{},key+'-finalize');last=s.document_id;
  }if(mounted.current)router.push('/documents/'+last);
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function commit(){if(!document?.draft)return;setBusy(true);setError('');try{
  const body={draft_id:document.draft.id,transaction:JSON.parse(canonical),source_confirmed:confirmed,reason,
   corrections:Object.entries(edits).map(([field_path,e])=>({field_path,value:e.value,page:e.page,reason})),
   ...(existing?{transaction_id:existing,expected_version:version}:{})};
  const result=await replayMutation<{id:string}>('documents/'+document.id+'/commit',body);if(mounted.current)router.push('/cases/'+result.id);
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!id)return <><div className="page-title"><div><h1>Upload a document</h1><p>A clear next step starts with the source.</p></div></div>{error?<div role="alert" className="error">{error}</div>:null}
 <section className="panel upload-panel"><h2>Start with your document</h2><p>Choose an invoice or expense receipt. We keep the original and ask about anything that’s unclear.</p>
 <div className="upload-dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)setFiles(Array.from(e.dataTransfer.files))}}><label>Document files<strong>Drop your file here, or choose one</strong><span>PDF, PNG or JPEG.{intake?` Up to ${Number((intake.maximum_bytes/1048576).toFixed(2))} MiB and ${intake.maximum_pages} pages.`:''}</span><input type="file" accept=".pdf,.png,.jpg,.jpeg" multiple disabled={busy} onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label>{files.length?<p className="selected-files" role="status">{files.map(f=>f.name).join(', ')}</p>:null}</div>
 <div className="upload-actions"><label>Document purpose<select value={kind} onChange={e=>setKind(e.target.value)} disabled={busy}><option value="AUTO">Auto · Detect document type</option><option value="VENDOR_INVOICE">Vendor invoice</option><option value="EMPLOYEE_RECEIPT">Employee expense</option><option value="SUPPORTING_DOCUMENT">Supporting document / PO</option></select></label><button onClick={upload} disabled={busy||!files.length}>{busy?'Storing originals…':'Upload and process'}</button></div>
 <p className="intake-safety">{intake?.malware_scanner==='NOT_CONFIGURED'?'Malware scanner: not configured.':intake?.malware_scanner==='CONFIGURED_UNVERIFIED'?'Malware scanner: configured; actual file scanning must still succeed.':intake?.malware_scanner==='UNAVAILABLE'?'Malware scanner: unavailable.':'Malware scanner status is unavailable.'}</p><details className="safety-details"><summary>What this means for your file</summary><p>{intake?.malware_required?'This scope requires a successful scan before preprocessing. Required-scanning deployments block intake until a working engine is connected.':intake?'This local scope permits bounded preprocessing without an available scanner. Use only authorized documents; this is not production malware protection.':'Check Admin system health. No clean scan result is asserted.'} Source text is treated as data, never as instructions.</p></details>
 </section><section className="panel records-panel"><div className="section-title"><h2>Recent documents</h2><Link href="/transactions">View finance history</Link></div>{items?<div className="table-wrap"><table><thead><tr><th>Source</th><th>Purpose</th><th>Processing</th></tr></thead><tbody>{items.map(d=><tr key={d.id}><td><Link href={'/documents/'+d.id}>{d.display_name}</Link></td><td>{d.source_type==='VENDOR_INVOICE'?'Vendor invoice':d.source_type==='EMPLOYEE_RECEIPT'?'Employee expense':'Supporting / type to confirm'}</td><td>{processingLabel(d.state)}<small>{processingError(d.last_error)}</small></td></tr>)}</tbody></table>{!items.length?<div className="empty"><h3>Your first upload starts here.</h3><p>Choose a file above. Its progress and original source will stay available.</p></div>:null}</div>:<p role="status">Loading documents…</p>}</section></>;
 if(!document)return <p role="status">{error||'Loading source document…'}</p>;
 const repeated=document.pages.flatMap((page,index)=>{if(!page.page_sha256||! /^[a-f0-9]{64}$/.test(page.page_sha256))return [];const first=document.pages.slice(0,index).find(p=>p.page_sha256===page.page_sha256);return first?[`${first.page} and ${page.page}`]:[]});
 return <><Link href="/documents" className="back">← Documents</Link><div className="page-title"><div><p className="eyebrow">Your preserved document</p><h1>{document.display_name}</h1><p>{processingLabel(document.state)} · {document.source_type==='VENDOR_INVOICE'?'Vendor invoice':document.source_type==='EMPLOYEE_RECEIPT'?'Employee expense':'Document type to confirm'}</p></div></div>{error?<div role="alert" className="error">{error}</div>:null}
 {working.has(document.state)?<div role="status" className="notice">Reading your document. This view updates automatically; you can leave and return to its history.</div>:null}
 {document.last_error?<div role="status" className="error">{processingError(document.last_error)} No finance decision has been made for this file.</div>:null}
 {repeated.length?<div className="notice" role="status"><strong>Check repeated source pages</strong><p>Pages {repeated.join('; ')} have identical rendered content. Their line items remain separate. Confirm whether these are copied pages; upload a corrected file if they are. The original pages remain available for review.</p></div>:null}
 <ol className="document-progress" aria-label="Document progress">{['PREPROCESS','EXTRACT','NORMALIZE','VALIDATE','FINALIZE'].map((stage,i)=>{const job=document.jobs.find(j=>j.stage===stage);return <li key={stage} className={job?.state==='SUCCEEDED'?'done':job?.state==='RUNNING'?'active':''}><span>{i+1}</span>{['Store original','Read facts','Normalize','Check uncertainty','Prepare review'][i]}</li>})}</ol>{document.last_error==='DOCUMENT_TYPE_UNCONFIRMED'?<section className="panel purpose-confirmation"><h2>Confirm the document type</h2><p>Printed labels could not establish a single document type. Your choice starts extraction and does not approve a payment.</p><label>Confirmed document type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="AUTO">Choose a type</option><option value="VENDOR_INVOICE">Vendor invoice</option><option value="EMPLOYEE_RECEIPT">Employee expense</option></select></label><label>Type confirmation reason<input value={reason} onChange={e=>setReason(e.target.value)} minLength={3}/></label><button disabled={busy||kind==='AUTO'||reason.trim().length<3} onClick={async()=>{setBusy(true);setError('');try{await mutate('documents/'+document.id+'/purpose',{source_type:kind,expected_generation:document.generation,reason},crypto.randomUUID());window.location.reload()}catch(e){setError((e as Error).message);setBusy(false)}}}>Confirm type and continue</button></section>:null}<div className="document-grid"><SourceViewer document={document} source={source}/><section className="panel"><h2>Check the source</h2><p className="hint">Extracted text needs confirmation against the source. Missing, ambiguous and illegible values stay unresolved. Corrections retain your reason and the original evidence.</p>
 {document.draft?.findings.length?<div className="notice"><strong>Needs your confirmation</strong><ul>{[...document.draft.findings].sort((a,b)=>Number(Boolean(b.message))-Number(Boolean(a.message))).map((f,i)=><li key={i}>{f.message||`${fieldLabel(f.field)}: ${f.code.includes('AMBIGUOUS')?'ambiguous; confirm the printed value':f.code.includes('MISSING')?'missing; provide source-backed information':'source or arithmetic check requires review'}`}</li>)}</ul><details><summary>Detailed validation findings</summary><pre>{JSON.stringify(document.draft.findings,null,2)}</pre></details></div>:null}
 <div className="source-key-facts">{['invoice_number','invoice_date','currency','total_amount'].map(field=>{const observation=document.observations.find(o=>o.field_path===field);return <div key={field}><button className="fact-source" data-field-path={field} disabled={!observation?.source} onClick={()=>setSource(observation?.source||null)}>{fieldLabel(field)}</button><strong>{observation?.state==='PRESENT'?observation.raw_value:'Needs confirmation'}</strong><small>{observation?observationLabel(observation.state):'Missing'}</small></div>})}</div><details className="all-source-facts"><summary>Review all extracted facts and correct values</summary>
 {document.observations.length?<div className="table-wrap"><table className="observation-table"><thead><tr><th>Field and evidence</th><th>Printed value</th><th>Normalized candidate</th><th>Your source correction</th></tr></thead><tbody>{document.observations.map(o=><tr key={o.id}><td><button className="evidence" data-field-path={o.field_path} aria-label={'View source for '+fieldLabel(o.field_path)} onClick={()=>setSource(o.source)}>{fieldLabel(o.field_path)}</button><small>{o.diagnostic?.startsWith('SOURCE_CELL_UNREAD:')?'Source value not read':observationLabel(o.state)} · {o.source?.page?`page ${o.source.page}`:'source unknown'}</small></td><td>{o.diagnostic?.startsWith('ROW_ASSOCIATION_UNCONFIRMED:')?<><span>Unassigned candidate</span><details><summary>Unassigned model candidate</summary><p>{o.raw_value??'No value generated for this inventory slot.'}</p></details></>:o.raw_value??'Not available'}{o.diagnostic?<details><summary>Evidence note</summary><p>{o.diagnostic}</p></details>:null}</td><td>{document.draft?.candidate[o.field_path]??'Unresolved'}{document.draft?.candidate[o.field_path]!=null?<small>Deterministically normalized · awaiting source confirmation</small>:null}<details><summary>Normalization evidence</summary><pre>{JSON.stringify(document.draft?.traces.filter(t=>t.field_path===o.field_path),null,2)}</pre></details></td><td><input aria-label={'Correct '+fieldLabel(o.field_path)} data-field-path={o.field_path} value={edits[o.field_path]?.value??''} placeholder="Leave unchanged" onChange={e=>setEdits(previous=>{const next={...previous};if(e.target.value)next[o.field_path]={value:e.target.value,page:previous[o.field_path]?.page||o.source?.page||1};else delete next[o.field_path];return next})}/>{edits[o.field_path]?<label>Correction source page<select value={edits[o.field_path].page} onChange={e=>setEdits(p=>({...p,[o.field_path]:{...p[o.field_path],page:Number(e.target.value)}}))}>{document.pages.map(p=><option key={p.page}>{p.page}</option>)}</select></label>:null}</td></tr>)}</tbody></table></div>:<p className="empty">No extraction observations are available. Resolve the displayed provider or safety status.</p>}
 </details><details className="advanced"><summary>Processing, provider and source metadata</summary><pre>{JSON.stringify({original:document.original,jobs:document.jobs,providers:document.extraction_runs,pages:document.pages},null,2)}</pre></details></section></div>
 {document.draft&&document.source_type!=='SUPPORTING_DOCUMENT'?<section className="panel"><h2>Confirm the facts, then screen the case</h2><p>Review the source, add a reason, and match the business records. Screening checks the facts and approvals; it does not authorize a payment.</p><label>Verification / correction reason<input value={reason} onChange={e=>setReason(e.target.value)} minLength={3}/></label><label className="check-label"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the source pages and confirm the observable facts.</label><details className="business-matching"><summary>Match supplier, budget and business references</summary><p>Choose records owned by your organization. Missing policy, approvals or capacity can place the case on hold.</p><BusinessFacts text={canonical} onChange={setCanonical} sourceDerived/></details><details><summary>Canonical draft and reference mapping</summary><label>Document canonical JSON<textarea value={canonical} onChange={e=>setCanonical(e.target.value)} rows={20}/></label></details><details><summary>Append a source-linked revision to an existing case</summary><label>Existing transaction UUID<input value={existing} onChange={e=>setExisting(e.target.value)}/></label><label>Expected current version<input type="number" min={1} value={version} onChange={e=>setVersion(Number(e.target.value))}/></label><p className="hint">Use the current case facts above to retain its other receipt items. Historical evaluations remain unchanged.</p></details><button onClick={commit} disabled={busy||working.has(document.state)||!confirmed||reason.length<3||document.segmentation_state==='UNCERTAIN'}>{busy?'Saving verified version…':'Verify facts and evaluate'}</button></section>:null}</>;
}

export function CaseSources({id}:{id:string}) {
 const [data,setData]=useState<{transaction_version:number;documents:{role:string;verified:boolean;document:Document}[];corrections:unknown[]}|null>(null),[error,setError]=useState('');
 const [available,setAvailable]=useState<DocList[]>([]),[selected,setSelected]=useState(''),[role,setRole]=useState('SUPPORT'),[item,setItem]=useState(0),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api<typeof data>('transactions/'+id+'/sources').then(setData).catch(e=>setError(e.message));api<{items:DocList[]}>('documents').then(r=>setAvailable(r.items.filter(d=>['READY','NEEDS_INPUT','DEPENDENCY_UNAVAILABLE'].includes(d.state)))).catch(()=>{})},[id]);
 async function attach(){if(!data)return;setBusy(true);setError('');try{
  await mutate('transactions/'+id+'/attachments',{expected_version:data.transaction_version,document_id:selected,role,reason,...role==='RECEIPT'?{item_index:item}:{}},crypto.randomUUID());window.location.reload();
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel"><h2>Source documents</h2><p className="hint">Follow the originals and confirmed facts behind this case. Corrections create new versions and keep earlier evidence.</p>{error?<p role="alert" className="error">{error}</p>:null}
 {data?.documents.map(link=><div key={link.document.id}><div className="case-source-link"><Link href={'/documents/'+link.document.id}>{link.role==='INVOICE'?'Original invoice':link.role==='RECEIPT'?'Original receipt':'Original document'}</Link><span className={'badge '+(link.verified?'pass':'review')}>{link.verified?'Source confirmed':'Awaiting source confirmation'}</span><Link href={'/documents/'+link.document.id+'?case='+id}>View source / append correction →</Link></div><details className="source-file-details"><summary>File details</summary><p>{link.document.display_name} · {link.role}</p></details></div>)}
 {data?.corrections.length?<details><summary>Source correction history</summary><pre>{JSON.stringify(data.corrections,null,2)}</pre></details>:null}
 <details><summary>Attach another document</summary><label>Stored document<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a stored document</option>{available.map(d=><option key={d.id} value={d.id}>{d.display_name} · {d.id.slice(-8)}</option>)}</select></label><label>Attachment role<select value={role} onChange={e=>setRole(e.target.value)}><option>SUPPORT</option><option>PO</option><option>RECEIPT</option><option>INVOICE</option></select></label>{role==='RECEIPT'?<label>Expense item index (first item = 0)<input type="number" min={0} max={199} value={item} onChange={e=>setItem(Number(e.target.value))}/></label>:null}<label>Attachment reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button onClick={attach} disabled={busy||!selected||reason.length<3}>Append version with attachment</button><p className="hint">Attachment creates a version; evaluate it again. Unverified source facts cannot clear the source control.</p></details></section>;
}
