'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {api,mutate,type Evaluation,type Canonical} from '@/lib/api';
import {SourceViewer,type DocumentDetail} from './documents';
type Json=Record<string,unknown>;
type Comparison={id:string;candidate_id:string;candidate_version:number;classification:string;signals:Json;disposition:string|null};
type Step={sequence:number;role:string;state:string;authorized:boolean;reason:string;actor_id:string|null;delegation_id:string|null};
type Approval={id:string;transaction_version:number;stale:boolean;requirements:{sequence:number;role:string}[];status:{steps:Step[]};actions:Json[]};
type Controls={transaction_version:number;controls:{budget:Json;allocations:Json[];approval:Json;receipt_usage:Json[];company_payments:Json[];aggregates:Json;split_pattern:Json|null;waivers:Json[]}|null};
function ErrorBox({message}:{message:string}){return message?<p role="alert" className="error">{message}</p>:null;}
function Table({rows,columns}:{rows:Json[];columns:[string,string][]}){return rows.length?<div className="table-wrap"><table><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id||i)}>{columns.map(([key])=><td key={key}>{typeof r[key]==='object'?JSON.stringify(r[key]):String(r[key]??'Unknown')}</td>)}</tr>)}</tbody></table></div>:<p className="hint">No records for this version.</p>;}
export function DemoIdentity(){
 const [choices,setChoices]=useState<{label:string;roles:string[]}[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/development/session').then(r=>r.json()).then(d=>setChoices(d.identities||[])).catch(()=>{});api<{label:string}>('me').then(d=>setSelected(d.label)).catch(()=>{});},[]);
 return choices.length>1?<div className="demo-identity"><label>Configured demo identity<select aria-label="Configured demo identity" value={selected} onChange={async e=>{try{const r=await fetch('/api/development/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:e.target.value})});if(!r.ok)throw new Error('Identity selection rejected');window.location.reload();}catch(e){setError((e as Error).message);}}}>{choices.map(c=><option key={c.label}>{c.label}</option>)}</select></label><small>Local synthetic identities. Permissions remain server configured.</small><ErrorBox message={error}/></div>:null;
}
export function FinanceControls({id,version,evaluation,onChange,refreshKey=0,canonical}:{id:string;version:number;evaluation:Evaluation|null;onChange:()=>Promise<unknown>;refreshKey?:number;canonical:Canonical}){
 const [data,setData]=useState<Controls|null>(null),[comparisons,setComparisons]=useState<Comparison[]>([]),[approvals,setApprovals]=useState<Approval[]>([]),[shares,setShares]=useState<Json[]>([]),[allocations,setAllocations]=useState<Json[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[share,setShare]=useState(''),[shareItem,setShareItem]=useState(''),[shareAmount,setShareAmount]=useState(''),[shareQuantity,setShareQuantity]=useState('1'),[waiver,setWaiver]=useState('EXP-003'),[source,setSource]=useState<Record<string,DocumentDetail>>({}),[roles,setRoles]=useState<string[]>([]),[reviewBinding,setReviewBinding]=useState<Record<string,unknown>>({});
 useEffect(()=>{void api<{roles:string[]}>('me').then(r=>setRoles(r.roles)).catch(()=>{})},[]);
 async function load(){const h=await api<{items:{id:string;review_version:number;owner_id:string|null}[]}>('transactions/'+id+'/review-history');const review=h.items[0];setReviewBinding(review?.owner_id?{review_case_id:review.id,expected_review_version:review.review_version}:{});const [d,c,a,s,l]=await Promise.all([api<Controls>('transactions/'+id+'/finance-controls'),api<{items:Comparison[]}>('transactions/'+id+'/duplicate-candidates'),api<{items:Approval[]}>('transactions/'+id+'/approval-requests'),api<{items:Json[]}>('transactions/'+id+'/receipt-shares'),api<{items:Json[]}>('transactions/'+id+'/matching-allocations')]);setData(d);setComparisons(c.items);setApprovals(a.items);setShares(s.items);setAllocations(l.items);}
 useEffect(()=>{let active=true;void load().catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id,version,evaluation?.evaluation_id,refreshKey]);
 async function action(path:string,body:unknown){setBusy(true);setError('');try{await mutate(path,path.endsWith('/resolutions')||path.endsWith('/waivers')||path.endsWith('/receipt-shares')?{...(body as Record<string,unknown>),...reviewBinding}:body,crypto.randomUUID());await onChange();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function openSource(did:string){try{setSource(s=>({...s,[did]:undefined as unknown as DocumentDetail}));const d=await api<DocumentDetail>('documents/'+did);setSource(s=>({...s,[did]:d}));}catch{setError('This source has structured evidence only; no uploaded page preview is available.');}}
 const selectedItem=canonical.items?.find(i=>i.id===shareItem)||canonical.items?.[0];
 const matching=evaluation?.rules.find(r=>r.rule_id==='GRN-001')?.observed;
 return <section className="panel finance-controls" aria-label="Finance matching and approvals"><h2>Finance matching & approvals</h2><p>Current facts v{version}. Capacity, approvals and resolutions remain pinned to their recorded versions.</p><ErrorBox message={error}/>{!data?<p role="status">Loading finance controls…</p>:<>
 <h3>Commercial matching</h3>{Array.isArray(matching)?<Table rows={matching as Json[]} columns={[["commercial_line_id","PO / contract line"],["requested_quantity","Current quantity"],["ordered_quantity","Ordered"],["prior_quantity","Prior allocation"],["accepted_quantity","Accepted"],["returned_quantity","Returned"],["reversed_quantity","Reversed"],["ordered_remaining","Ordered remaining"],["received_remaining","Accepted remaining"],["quantity_shortfall","Shortfall"],["unit_price_variance","Price variance"],["applied_tolerance","Tolerance"]]}/>:<p className="hint">Commercial matching does not apply, or awaits an activated finance evaluation.</p>}
 <h3>Budget capacity</h3>{data.controls?.budget?<dl className="budget-summary">{Object.entries(data.controls.budget).filter(([k])=>k!=='ledger_event_ids').map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(v)}</dd></div>)}</dl>:<p className="hint">No Phase-3 budget result for this version.</p>}
 <h3>Allocation lifecycle</h3><Table rows={allocations} columns={[["kind","Resource"],["amount","Amount"],["quantity","Quantity"],["currency","Currency"],["state","State"],["transaction_version","Version"]]}/>
 <h3>Duplicate comparisons</h3>{!comparisons.length?<p className="hint">No persisted candidates for this version. Search completion appears in the evaluation.</p>:comparisons.map(c=><article className="comparison" key={c.id}><div className="section-title"><h4>{c.classification.replaceAll('_',' ')}</h4><span>{c.disposition||'Unresolved'} · candidate v{c.candidate_version}</span></div><div className="comparison-grid"><div><h5>Current facts</h5><pre>{JSON.stringify(c.signals.source_facts,null,2)}</pre>{((c.signals.source_document_ids||[]) as string[]).map(did=><button className="secondary" key={did} onClick={()=>void openSource(did)}>View source {did.slice(-8)}</button>)}</div><div><h5>Compared facts</h5><pre>{JSON.stringify(c.signals.candidate_facts,null,2)}</pre>{((c.signals.candidate_document_ids||[]) as string[]).map(did=><button className="secondary" key={did} onClick={()=>void openSource(did)}>View compared source {did.slice(-8)}</button>)}</div></div><details><summary>Signals, field differences and lifecycle</summary><pre>{JSON.stringify(c.signals,null,2)}</pre></details>{!c.disposition&&roles.includes('DUPLICATE_REVIEWER')?<div className="actions">{['DISTINCT','CONFIRMED_DUPLICATE','SHARED_RECEIPT_ALLOCATION'].map(disposition=><button disabled={busy||reason.trim().length<3} key={disposition} onClick={()=>void action('duplicate-candidates/'+c.id+'/resolutions',{expected_version:version,disposition,reason,evidence_ids:[id,c.candidate_id]})}>{disposition.replaceAll('_',' ')}</button>)}</div>:null}</article>)}
 <div className="comparison-grid">{Object.entries(source).filter(([,d])=>d).map(([did,d])=><div className="comparison-source" key={did}><h4>Source {did.slice(-8)}</h4><SourceViewer document={d}/></div>)}</div>
 <h3>Approval chain</h3><button disabled={busy||reason.trim().length<3||!roles.includes('FINANCE_REVIEWER')} onClick={()=>void action('transactions/'+id+'/approval-requests',{expected_version:version,reason})}>Request current approvals</button>{approvals.map(a=><article key={a.id}><h4>Request for v{a.transaction_version} {a.stale?'— stale facts':''}</h4><Table rows={a.status.steps as unknown as Json[]} columns={[["sequence","Order"],["role","Required role"],["state","Status"],["actor_id","Actor"],["authorized","Authority valid"],["delegation_id","Delegation"]]}/>{!a.stale?a.requirements.map(s=><div className="actions" key={s.sequence}><button disabled={busy||reason.trim().length<3} onClick={()=>void action('approval-requests/'+a.id+'/actions',{expected_version:version,sequence:s.sequence,action:'APPROVED',reason})}>Approve step {s.sequence} · {s.role}</button><button className="secondary" disabled={busy||reason.trim().length<3} onClick={()=>void action('approval-requests/'+a.id+'/actions',{expected_version:version,sequence:s.sequence,action:'DECLINED',reason})}>Decline step {s.sequence}</button></div>):null}<details><summary>Immutable actions and rejection reasons</summary><pre>{JSON.stringify(a.actions,null,2)}</pre></details></article>)}
 <h3>Receipt shares & policy aggregates</h3><Table rows={shares} columns={[["document_id","Receipt"],["item_id","Item"],["amount","Authorized share"],["employee_id","Claimant"],["transaction_version","Version"]]}/>{data.controls?<details><summary>Policy limits, receipt usage, company payments and split findings</summary><pre>{JSON.stringify({receipt_usage:data.controls.receipt_usage,company_payments:data.controls.company_payments,aggregates:data.controls.aggregates,split_pattern:data.controls.split_pattern},null,2)}</pre></details>:null}<details><summary>Authorize a receipt share</summary>{canonical.items?.length?<><label>Expense item for receipt share<select value={selectedItem?.id||''} onChange={e=>{setShareItem(e.target.value);setShareAmount('')}}>{canonical.items.map((i,n)=><option key={i.id} value={i.id||''}>Expense item {n+1} · {i.category} · {i.claimed_amount} {i.currency}</option>)}</select></label><p>The receipt already linked to this expense item provides source evidence.</p><label>Authorized share amount<input inputMode="decimal" value={shareAmount||selectedItem?.claimed_amount||''} onChange={e=>setShareAmount(e.target.value)}/></label><label>Receipt share quantity<input inputMode="decimal" value={shareQuantity} onChange={e=>setShareQuantity(e.target.value)}/></label></>:<p>No expense items are linked to this transaction.</p>}<details><summary>Advanced receipt share facts</summary><label>Share facts<textarea aria-label="Receipt share facts" value={share} onChange={e=>setShare(e.target.value)} placeholder='{"document_id":"…","item_id":"…","amount":"600.00","quantity":"1"}' rows={4}/></label></details><button disabled={busy||reason.trim().length<3||(!share&&!selectedItem?.source_document_id)||!roles.includes('RECEIPT_ALLOCATOR')} onClick={()=>{try{const facts=share?JSON.parse(share):{document_id:selectedItem?.source_document_id,item_id:selectedItem?.id,amount:shareAmount||selectedItem?.claimed_amount,quantity:shareQuantity};void action('transactions/'+id+'/receipt-shares',{...facts,expected_version:version,reason,evidence_ids:[id]});}catch{setError('Supply valid receipt share facts.');}}}>Authorize share</button></details>
 <h3>Explicit rule waivers</h3><Table rows={(data.controls?.waivers||[])} columns={[["rule_id","Rule"],["rule_version","Version"],["actor_id","Authority"],["reason","Reason"],["expires_at","Expiry"]]}/><p className="hint">Ordinary approval does not waive a failed rule. Original findings remain visible.</p><label>Rule for waiver<input value={waiver} onChange={e=>setWaiver(e.target.value)}/></label><button disabled={busy||reason.trim().length<3||!evaluation||!roles.includes('FINANCE_CONTROLLER')} onClick={()=>{const r=evaluation?.rules.find(r=>r.rule_id===waiver);void action('transactions/'+id+'/waivers',{expected_version:version,rule_id:waiver,reason,expires_at:new Date(Date.now()+86400000).toISOString(),evidence_ids:r?.evidence.slice(0,1).map(e=>e.id)||[]});}}>Request configured waiver</button>
 <label>Reason for control action<input aria-label="Control action reason" value={reason} onChange={e=>setReason(e.target.value)} minLength={3}/></label><p className="hint">The server checks your logged-in identity, current version, authority and evidence.</p>
 </>}</section>;
}
export function ReferenceImports(){
 const [items,setItems]=useState<Json[]>([]),[text,setText]=useState(''),[reason,setReason]=useState(''),[source,setSource]=useState('SYNTHETIC_LOCAL'),[sourceVersion,setVersion]=useState('v1'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 async function load(){const r=await api<{items:Json[]}>('reference-imports');setItems(r.items);setLoaded(true);}
 useEffect(()=>{void load().catch(e=>{setError(e.message);setLoaded(true);});},[]);
 async function action(path:string,body:unknown){setBusy(true);setError('');try{await mutate(path,body,crypto.randomUUID());await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="page-title"><div><h1>Reference imports</h1><p>Stage, validate and activate an approved source version. Existing evaluations retain their snapshots.</p></div></div><ErrorBox message={error}/><section className="panel"><h2>Stage reference records</h2><label>Source system<input value={source} onChange={e=>setSource(e.target.value)}/></label><label>Source version<input value={sourceVersion} onChange={e=>setVersion(e.target.value)}/></label><label>Reference records JSON<textarea aria-label="Reference records JSON" rows={10} value={text} onChange={e=>setText(e.target.value)} placeholder='[{"kind":"vendors","payload":{…}}]'/></label><label>Import / activation reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!text||reason.trim().length<3} onClick={()=>{try{void action('reference-imports',{source_system:source,source_version:sourceVersion,records:JSON.parse(text),reason});}catch{setError('Enter a valid array of reference records.');}}}>Stage import</button></section><section className="panel"><h2>Import batches</h2>{!loaded?<p role="status">Loading reference batches…</p>:!items.length?<p>No staged imports. Add a source batch above.</p>:items.map(r=><article className="reference-batch" key={String(r.id)}><h3>{String(r.source_system)} / {String(r.source_version)} · {String(r.state)}</h3><details><summary>Validation findings and source records</summary><pre>{JSON.stringify({validation:r.validation,records:r.records},null,2)}</pre></details>{['STAGED','INVALID','VALID'].includes(String(r.state))?<button disabled={busy} onClick={()=>void action('reference-imports/'+r.id+'/validate',{})}>Validate batch</button>:null}{r.state==='VALID'?<button disabled={busy||reason.trim().length<3} onClick={()=>void action('reference-imports/'+r.id+'/activate',{reason})}>Activate validated batch</button>:null}</article>)}</section></>;
}
