'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';
type Scenario={key:string;label:string;decision:string;transaction_version:number;current_version:number;case_url:string;report_url:string;document_url:string|null;original_report_url:string|null;provider:string|null;source_corrections:number|null};
type Walkthrough={ready:boolean;message:string;items:Scenario[]};
export function Hackathon(){
 const [data,setData]=useState<Walkthrough|null>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;api<Walkthrough>('development/scenarios').then(value=>{if(active)setData(value)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 return <><div className="page-title"><div><h1>Hackathon walkthrough</h1><p>Prepared synthetic cases screened by the actual finance engine. No payments are executed.</p></div><Link className="button" href="/documents">Upload another document</Link></div>
 {error?<p role="alert" className="error">{error}</p>:!data?<p role="status">Loading computed scenarios…</p>:<><p className="notice" role="status">{data.message}</p>{data.items.length?<section className="panel" aria-label="Computed demo scenarios"><div className="table-wrap" tabIndex={0} aria-label="Scrollable demo scenario table"><table className="demo-scenarios"><thead><tr><th scope="col">Scenario</th><th scope="col">Retained screening</th><th scope="col">Inspect evidence</th></tr></thead><tbody>{data.items.map(row=><tr key={row.key}><td><Link href={row.case_url}>{row.label}</Link>{row.provider?<small>{row.provider} · source corrections: {row.source_corrections??'unknown'}</small>:null}</td><td><span className={'badge '+row.decision.toLowerCase()}>{row.decision}</span><small>Evaluation version {row.transaction_version}{row.current_version!==row.transaction_version?` · current version ${row.current_version}`:''}</small></td><td><Link href={row.report_url}>View retained report</Link>{row.document_url?<p><Link href={row.document_url}>View actual source and extraction</Link></p>:null}{row.original_report_url?<p><Link href={row.original_report_url}>View original HOLD</Link></p>:null}</td></tr>)}</tbody></table></div><p className="hint">On a narrow screen, scroll the table to inspect each case and its evidence links.</p></section>:<section className="panel"><h2>Prepare the walkthrough</h2><p>Select <strong>Hackathon finance reviewer</strong> in the development identity selector. If the scenarios are not prepared, run <code>./scripts/prepare-demo.sh</code> on the local host.</p></section>}</>}
 <section className="panel"><h2>What this demo verifies</h2><p>The visual invoice uses the pinned Qwen model and actual TypeLLM generation, followed by source verification, matching, independent approvals and deterministic screening. Corrections retain earlier versions and evaluations.</p><p>These synthetic development examples establish compatibility. Representative adjudicated history is still required for supervised finance-risk training; commercial model licensing and live Azure provisioning remain separate decisions.</p></section></>;
}
