'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {api,mutate,type Case,type Evaluation,type Canonical} from '@/lib/api';
import type {DocumentDetail} from './documents';

type Review={id:string;review_version:number;transaction_version:number;current_transaction_version:number;owner_id:string|null;state:string;permitted_actions:string[];created_at:string};
type Me={actor_id:string;roles:string[];label:string};
type Timeline={sequence:number;action:string;actor_id:string;created_at:string;version:number;reason:string;evidence:Record<string,string>};
const human=(value:string)=>value.toLowerCase().replaceAll('_',' ');
const open=['OPEN','ASSIGNED','AWAITING_INFORMATION'];

export function ReviewWorkflow({record,evaluation,onChange}:{record:Case;evaluation:Evaluation|null;onChange:()=>Promise<unknown>}){
 const [reviews,setReviews]=useState<Review[]|null>(null),[me,setMe]=useState<Me|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[comment,setComment]=useState(''),[requested,setRequested]=useState(''),[field,setField]=useState('invoice_number'),[value,setValue]=useState(''),[page,setPage]=useState(1),[sources,setSources]=useState<{document:DocumentDetail}[]>([]),[target,setTarget]=useState('');
 const noticeRef=useRef<HTMLParagraphElement>(null);
 async function load(){const [history,identity,source]=await Promise.all([api<{items:Review[]}>('transactions/'+record.id+'/review-history'),api<Me>('me'),api<{documents:{document:DocumentDetail}[]}>('transactions/'+record.id+'/sources')]);setReviews(history.items);setMe(identity);setSources(source.documents);if(record.branch!=='VENDOR_INVOICE'&&field==='invoice_number')setField('claim_number')}
 useEffect(()=>{setReviews(null);void load().catch(e=>setError(e.message))},[record.id,record.version,evaluation?.evaluation_id]);
 const review=reviews?.find(r=>open.includes(r.state))||reviews?.[0];
 const owned=!!review&&review.owner_id===me?.actor_id;
 async function command(action:string,extra:Record<string,unknown>={},assignment=false){if(!review)return;setBusy(true);setError('');setNotice('');try{await mutate('reviews/'+review.id+(assignment?'/assign':'/actions'),{expected_review_version:review.review_version,expected_transaction_version:record.version,reason_code:'FINANCE_REVIEW',comment:comment||'Finance reviewer inspected the current case',action,...extra},crypto.randomUUID());setNotice(action==='CORRECT_FIELD'?'Correction saved. Fresh screening and approvals are required.':human(action)+' recorded.');await onChange();await load();noticeRef.current?.focus()}catch(e){setError((e as Error).message+' Refresh the review before trying again.');/* Preserve the stale form until the user explicitly refreshes. */}finally{setBusy(false)}}
 async function correct(e:React.FormEvent){e.preventDefault();if(!evaluation)return;const payload=structuredClone(record.versions.at(-1)!.payload);const previous=payload[field as keyof Canonical];if(String(previous??'')===value){setError('Enter a different value to create a correction.');return}const evidence=evaluation.rules.flatMap(r=>r.evidence);const doc=sources.find(s=>s.document.observations.some(o=>o.field_path===field))?.document;
  if(doc?.draft){const sourceEvidence=evidence.filter(e=>(e.reference as {document_id?:string}).document_id===doc.id);if(!sourceEvidence.length){setError('Source-linked evidence is required for this field.');return}await command('CORRECT_FIELD',{document_id:doc.id,evidence_ids:sourceEvidence.slice(0,20).map(e=>e.id),document_commit:{draft_id:doc.draft.id,transaction:payload,source_confirmed:true,reason:comment,first_page:1,last_page:doc.pages.length,corrections:[{field_path:field,value,page,reason:comment}]}})}
  else {const changed={...payload,[field]:value};await command('CORRECT_FIELD',{transaction:changed,evidence_ids:evidence.slice(0,1).map(e=>e.id)})}}
 if(!reviews)return <section className="panel" aria-label="Review workflow"><h2>Review workflow</h2>{error?<p role="alert">{error}</p>:<p role="status">Loading current ownership…</p>}</section>;
 if(!review)return <section className="panel"><h2>Review workflow</h2><p>No exception case has been opened for this transaction.</p></section>;
 const writable=me?.roles.includes('FINANCE_REVIEWER');
 const p=record.versions.at(-1)!.payload;const fields=record.branch==='VENDOR_INVOICE'?['invoice_number','invoice_date','currency','total_amount','vendor_id','po_id','contract_id']:['claim_number','expense_date','currency','requested_amount','employee_id','category','merchant'];
 return <section className="panel" aria-label="Review workflow"><div className="section-title"><h2>Review workflow</h2><button className="secondary" onClick={()=>{setError('');void load().catch(e=>setError(e.message))}} disabled={busy}>Refresh review</button></div><p><strong>{review.state==='OPEN'?'Unassigned':human(review.state)}</strong> · Review version {review.review_version} · {owned?`Owned by ${me?.label}`:review.owner_id?'Assigned to another reviewer':'No owner'}</p><p ref={noticeRef} tabIndex={-1} role="status">{notice}</p>{error?<p role="alert" className="error">{error}</p>:null}
 {writable&&open.includes(review.state)?<><div className="actions">{!review.owner_id?<button onClick={()=>void command('CLAIM',{},true)} disabled={busy}>Claim case</button>:owned?<button className="secondary" onClick={()=>void command('RELEASE',{},true)} disabled={busy}>Release case</button>:null}</div>{me?.roles.includes('REVIEW_MANAGER')?<details><summary>Reassign ownership</summary><label>Authorized reviewer ID<input value={target} onChange={e=>setTarget(e.target.value)}/></label><button disabled={busy||!target} onClick={()=>void command('REASSIGN',{owner_id:target},true)}>Reassign case</button></details>:null}</>:null}
 {owned&&writable?<><label>Review reason<input value={comment} onChange={e=>setComment(e.target.value)} minLength={3} maxLength={500}/></label>{open.includes(review.state)?<><form onSubmit={e=>{e.preventDefault();void command('REQUEST_INFORMATION',{requested_input:requested})}}><label>Requested evidence or information<textarea value={requested} onChange={e=>setRequested(e.target.value)} minLength={3} maxLength={1000} required rows={2}/></label><button disabled={busy||comment.length<3}>Request information</button><p className="hint">Records an internal request. No message is sent.</p></form><details><summary>Correct a canonical or source field</summary><form onSubmit={correct}><label>Field to correct<select value={fields.includes(field)?field:fields[0]} onChange={e=>{setField(e.target.value);setValue('')}}>{fields.map(f=><option key={f} value={f}>{human(f)}</option>)}</select></label><p>Current canonical value: <strong>{String(p[(fields.includes(field)?field:fields[0]) as keyof Canonical]??'Unknown')}</strong></p><label>Corrected value<input value={value} onChange={e=>setValue(e.target.value)} required maxLength={500}/></label>{sources.length?<label>Evidence page<input type="number" min={1} max={30} value={page} onChange={e=>setPage(Number(e.target.value))}/></label>:null}<p className="hint">The source observation and previous canonical version remain in history. Printed amount changes must still reconcile with lines and tax.</p><button disabled={busy||comment.length<3||!evaluation}>Save field correction</button></form></details><button className="secondary" disabled={busy||comment.length<3} onClick={()=>void command('CANCEL_TRANSACTION')}>Cancel transaction</button></>:null}{record.eligible&&['SUPERSEDED','OPEN','ASSIGNED'].includes(review.state)?<button disabled={busy||comment.length<3} onClick={()=>void command('RESOLVE_EXCEPTION')}>Resolve exception</button>:null}</>:null}
 <details><summary>Review identifiers and versions</summary><p className="uuid">{review.id} · Source transaction version {review.transaction_version}</p></details></section>
}

export function AuditTimeline({id,version}:{id:string;version:number}){
 const [items,setItems]=useState<Timeline[]|null>(null),[next,setNext]=useState<number|null>(null),[error,setError]=useState('');
 async function load(after=0){try{const r=await api<{items:Timeline[];next_sequence:number|null}>(`transactions/${id}/timeline?limit=50&after_sequence=${after}`);setItems(previous=>after?[...(previous||[]),...r.items]:r.items);setNext(r.next_sequence)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[id,version]);
 return <section className="panel" aria-label="Audit timeline"><div className="section-title"><h2>Audit timeline</h2><button className="secondary" onClick={()=>void load()}>Refresh timeline</button></div>{error?<p role="alert" className="error">{error}</p>:!items?<p role="status">Loading retained actions…</p>:!items.length?<p>No retained actions are available.</p>:<ol className="audit-timeline">{items.map(e=><li key={e.sequence}><strong>{human(e.action)}</strong><p>{e.reason}</p><small><time dateTime={e.created_at}>{new Date(e.created_at).toLocaleString()}</time> · Version {e.version??'—'}</small><details><summary>Actor and evidence</summary><p className="uuid">Actor {e.actor_id} · Audit sequence {e.sequence}</p>{e.evidence.evaluation_id?<Link href={'/reports/'+e.evidence.evaluation_id}>View retained evaluation</Link>:null}{e.evidence.document_id?<Link href={'/documents/'+e.evidence.document_id}>View source document</Link>:null}</details></li>)}</ol>}{next?<button onClick={()=>void load(next)}>Load more timeline events</button>:null}</section>
}

type Job={id:string;kind:string;state:string;stage:string;attempts:number;maximum_attempts:number;retryable:boolean;manual_retries:number;last_error:string;transaction_id:string|null;document_id:string|null;first_failure_at:string|null;last_failure_at:string|null;correlation_id:string};
type Dashboard={counts:Record<string,number>;open_cases:number;oldest_age_seconds:number|null;by_state:Record<string,number>;by_branch:Record<string,number>;by_owner:{owner_id:string|null;count:number}[];by_reason:Record<string,number>;failures:Record<string,Record<string,number>>;recent_activity:{action:string;reason:string;created_at:string}[];measured_at:string};
export function Operations(){
 const [dashboard,setDashboard]=useState<Dashboard|null>(null),[jobs,setJobs]=useState<Job[]|null>(null),[me,setMe]=useState<Me|null>(null),[deps,setDeps]=useState<Record<string,string>>({}),[error,setError]=useState(''),[state,setState]=useState('FAILED'),[offset,setOffset]=useState(0),[next,setNext]=useState<number|null>(null),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[repairs,setRepairs]=useState<{code:string;status:string;object_id:string}[]|null>(null);
 async function load(){const [d,j,m,dependencies]=await Promise.all([api<Dashboard>('operations/dashboard'),api<{items:Job[];next_offset:number|null}>(`operations/jobs?state=${state}&offset=${offset}`),api<Me>('me'),api<Record<string,string>>('operations/dependencies')]);setDashboard(d);setJobs(j.items);setNext(j.next_offset);setMe(m);setDeps(dependencies)}
 useEffect(()=>{setJobs(null);setError('');void load().catch(e=>setError(e.message))},[state,offset]);
 async function retry(job:Job){setBusy(true);setError('');try{await mutate(`operations/jobs/${job.kind}/${job.id}/retry`,{expected_attempts:job.attempts,reason},crypto.randomUUID());await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function reconcile(){setBusy(true);setError('');try{const r=await mutate<{findings:{code:string;status:string;object_id:string}[]}>('operations/reconcile',{reason},crypto.randomUUID());setRepairs(r.findings);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><div className="page-title"><div><h1>Operations</h1><p>Persisted queue, review activity and recoverable failures.</p></div><button onClick={()=>void load().catch(e=>setError(e.message))}>Refresh operations</button></div>{error?<p role="alert" className="error">{error}</p>:null}{dashboard?<><section className="panel"><h2>Review workload</h2><div className="stats">{['PASS','REVIEW','HOLD'].map(s=><Link href={'/transactions?decision='+s} key={s}><strong>{dashboard.counts[s]||0}</strong><span>{s}</span></Link>)}</div><p>{dashboard.open_cases} open cases. Oldest case: {dashboard.oldest_age_seconds===null?'No open cases':Math.floor(dashboard.oldest_age_seconds/3600)+' hours'}.</p><div className="case-grid"><div><h3>Cases by reason</h3><ul>{Object.entries(dashboard.by_reason).map(([rule,count])=><li key={rule}><Link href={'/queue?reason='+rule}>{rule}: {count} cases</Link></li>)}</ul></div><div><h3>Cases by owner</h3><ul>{dashboard.by_owner.map(r=><li key={r.owner_id||'none'}><Link href={'/queue?owner='+(r.owner_id||'unassigned')}>{r.owner_id?`Reviewer ${r.owner_id.slice(-8)}`:'Unassigned'}: {r.count}</Link></li>)}</ul><h3>Cases by branch</h3>{Object.entries(dashboard.by_branch).map(([b,c])=><p key={b}><Link href={'/queue?branch='+b}>{human(b)}: {c}</Link></p>)}</div></div><h3>Recent review activity</h3>{dashboard.recent_activity.length?<ul>{dashboard.recent_activity.map((e,i)=><li key={i}>{human(e.action)} — {e.reason} <time dateTime={e.created_at}>{new Date(e.created_at).toLocaleString()}</time></li>)}</ul>:<p>No review activity has been recorded.</p>}</section></>:!error?<p role="status">Loading operational measurements…</p>:null}
 <section className="panel"><h2>Processing failures</h2><label>Job state<select value={state} onChange={e=>{setState(e.target.value);setOffset(0)}}><option value="FAILED">Dead letter / terminal failure</option><option value="RETRYABLE">Retryable failure</option><option value="RUNNING">Processing</option></select></label>{!jobs?<p role="status">Loading authorized job details…</p>:!jobs.length?<p className="empty">No jobs match this state.</p>:<div className="table-wrap"><table><thead><tr><th scope="col">Related record</th><th scope="col">Stage / state</th><th scope="col">Attempts</th><th scope="col">Safe error</th><th scope="col">Recovery</th></tr></thead><tbody>{jobs.map(j=><tr key={j.kind+j.id}><td>{j.transaction_id?<Link href={'/cases/'+j.transaction_id}>Transaction {j.transaction_id.slice(-8)}</Link>:<Link href={'/documents/'+j.document_id}>Document {j.document_id?.slice(-8)}</Link>}<details><summary>Failure details</summary><p>First failure: {j.first_failure_at||'Unavailable'}</p><p>Last failure: {j.last_failure_at||'Unavailable'}</p><p className="uuid">Correlation {j.correlation_id}</p></details></td><td>{human(j.stage)} / {human(j.state)}</td><td>{j.attempts} / {j.maximum_attempts}</td><td>{j.last_error||'None'}</td><td>{me?.roles.includes('OPERATIONS_ADMIN')&&j.retryable&&j.manual_retries<2?<button disabled={busy||reason.length<3} onClick={()=>void retry(j)}>Retry job</button>:j.retryable?'Authorized recovery required':'Resolve input or dependency configuration'}</td></tr>)}</tbody></table></div>}<div className="actions">{offset>0?<button onClick={()=>setOffset(Math.max(0,offset-50))}>Previous job page</button>:null}{next!==null?<button onClick={()=>setOffset(next)}>Next job page</button>:null}</div></section>
 <section className="panel"><h2>Dependencies</h2><dl>{Object.entries(deps).map(([k,v])=><div key={k}><dt>{human(k)}</dt><dd>{v}</dd></div>)}</dl><p>{deps.enterprise_vlm==='AVAILABLE'?'Document extraction provider is healthy. Extracted facts still require validation and source review.':'Document extraction is not currently verified as available. Required unavailable extraction stays incomplete.'}</p></section>{me?.roles.includes('OPERATIONS_ADMIN')?<section className="panel"><h2>Operational recovery</h2><label>Recovery reason<input value={reason} onChange={e=>setReason(e.target.value)} minLength={3} maxLength={500}/></label><button disabled={busy||reason.length<3} onClick={()=>void reconcile()}>Run reconciliation</button><p>Safe repairs append audit records. Originals and unresolved artifacts are preserved.</p>{repairs?<div role="status">{repairs.length?<ul>{repairs.map((f,i)=><li key={i}>{human(f.code)}: {human(f.status)}</li>)}</ul>:<p>No inconsistencies found within the inspected batch.</p>}</div>:null}</section>:null}</>
}

export function ReportExports({id}:{id:string}){
 const [me,setMe]=useState<Me|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{void api<Me>('me').then(setMe).catch(e=>setError(e.message))},[]);
 async function download(format:string){setBusy(true);setError('');try{const r=await mutate<{download_url:string}>(`evaluations/${id}/exports`,{format},crypto.randomUUID());const a=document.createElement('a');a.href=r.download_url.replace('/api/v1/','/api/');a.download='screening-'+id+'.'+format;document.body.append(a);a.click();a.remove()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="report-actions">{me&&me.roles.some(r=>['AUDITOR','REPORT_EXPORTER'].includes(r))?<div className="actions">{['json','html','csv'].map(format=><a key={format} className="button secondary" href="#" aria-disabled={busy} onClick={e=>{e.preventDefault();if(!busy)void download(format)}}>Download {format.toUpperCase()}</a>)}</div>:<p>Report downloads require explicit export permission.</p>}{error?<p role="alert" className="error">{error}</p>:null}</div>
}
