import {test,expect,type APIRequestContext,type Page} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
const origin='http://127.0.0.1:3000';
async function post(request:APIRequestContext,path:string,data:unknown){const r=await request.post('/api/'+path,{headers:{Origin:origin,'Idempotency-Key':randomUUID()},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json()}
async function useIdentity(page:Page,label:string){await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),page.getByLabel('Configured demo identity').selectOption(label)]);await expect(page.getByLabel('Configured demo identity')).toHaveValue(label)}
const source=(kind:string)=>JSON.parse(readFileSync(resolve('../../data/synthetic/reference/'+kind+'.json'),'utf8')).records;
async function invoice(request:APIRequestContext){
 const p=await (await request.get('/api/development/templates/vendor')).json();p.invoice_number='SYNTHETIC-P5-'+randomUUID();
 const budget=structuredClone(source('budgets')[0]),po=structuredClone(source('purchase_orders')[0]),line=structuredClone(po.lines[0]),grn=structuredClone(source('goods_receipts')[0].lines[0]),doc=structuredClone(source('documents').find((d:{id:string})=>d.id===p.source_document_id)),vendor=structuredClone(source('vendors').find((v:{id:string})=>v.id===p.vendor_id));
 vendor.id=randomUUID();vendor.legal_name='FICTIONAL P5 SUPPLIER '+vendor.id.slice(-8);budget.id=randomUUID();budget.ledger=[{id:randomUUID(),entry_type:'ALLOCATION',amount:'1000000.00',currency:'INR'}];po.id=randomUUID();po.vendor_id=vendor.id;po.budget_id=budget.id;po.approved_ceiling_amount='1000000.00';delete po.lines;line.id=randomUUID();line.po_id=po.id;line.vendor_id=vendor.id;line.ordered_quantity='100';grn.id=randomUUID();grn.po_id=po.id;grn.po_line_id=line.id;grn.accepted_quantity='100';grn.returned_quantity='0';grn.reversed_quantity='0';doc.id=randomUUID();doc.facts.invoice_number=p.invoice_number;doc.facts.vendor_name=vendor.legal_name;
 p.vendor_id=vendor.id;p.budget_id=budget.id;p.po_id=po.id;p.lines[0].po_line_id=line.id;p.lines[0].grn_line_id=grn.id;p.source_document_id=doc.id;
 const batch=await post(request,'reference-imports',{source_system:'SYNTHETIC_PHASE5_BROWSER',source_version:randomUUID(),reason:'Independent fictional intelligence evidence',records:[{kind:'vendors',payload:vendor},{kind:'budgets',payload:budget},{kind:'purchase_orders',payload:po},{kind:'po_lines',payload:line},{kind:'grn_lines',payload:grn},{kind:'documents',payload:doc}]});
 expect((await post(request,'reference-imports/'+batch.id+'/validate',{})).state).toBe('VALID');await post(request,'reference-imports/'+batch.id+'/activate',{reason:'Activate independently validated fictional evidence'});
 for(let i=0;i<5;i++){const prior=structuredClone(p);prior.invoice_number='P5-PRIOR-'+randomUUID();prior.source_document_id=null;prior.invoice_date='2026-09-01';prior.total_amount='1000';prior.subtotal_amount='1000';prior.tax_amount='0';prior.lines[0].quantity='1';prior.lines[0].unit_price='1000';prior.lines[0].net_amount='1000';prior.lines[0].tax_rate='0';prior.lines[0].tax_amount='0';prior.lines[0].gross_amount='1000';await post(request,'transactions',prior)}
 const c=await post(request,'transactions',p);await post(request,'transactions/'+c.id+'/evaluate',{expected_version:1,reason:'Screen a fictional Phase-5 review case'});return {id:c.id,p}
}

test('point-in-time intelligence is separate from controls and feedback preserves taxonomy',async({page})=>{
 const {id}=await invoice(page.request);await page.goto('/cases/'+id);await expect(page.locator('.page-title .badge')).toHaveText('HOLD',{timeout:30000});const intelligence=page.getByRole('region',{name:'Transaction intelligence'});
 await expect(intelligence).toContainText('RULES_ONLY');await expect(intelligence).toContainText('not configured');await intelligence.getByText('Point-in-time feature values and missing sources').click();await expect(intelligence.getByRole('row').filter({has:page.getByRole('cell',{name:'vendor amount ratio',exact:true})})).toContainText('23.6');
 await page.getByRole('button',{name:'Claim case',exact:true}).click();await expect(page.getByRole('button',{name:'Release case',exact:true})).toBeVisible();await intelligence.getByLabel('Adjudication label').selectOption('DOCUMENT_CORRECTION_ONLY');await intelligence.getByLabel('Adjudication reason').fill('Source facts require correction, no policy exception has been confirmed');await intelligence.getByRole('button',{name:'Record adjudication'}).click();await expect(intelligence).toContainText('document correction only');await expect(intelligence).toContainText('(provisional)');await expect(page.locator('.page-title .badge')).toHaveText('HOLD');
 await page.getByRole('button',{name:'Refresh timeline'}).click();await expect(page.getByRole('region',{name:'Audit timeline'})).toContainText('feedback label created');await page.screenshot({path:'../../output/playwright/phase5-feature-feedback.png',fullPage:true});await intelligence.screenshot({path:'../../output/playwright/phase5-intelligence-panel.png'});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('governance permissions dataset gate independent approval shadow escalation and rollback',async({page})=>{
 test.setTimeout(90000); // Several actual persisted transitions and independent actors on a shared host.
 const ordinary=(await (await page.request.get('/api/me')).json()).label;const {id}=await invoice(page.request);
 await page.goto('/intelligence');await expect(page.getByRole('heading',{name:'Governance access required'})).toBeVisible();await useIdentity(page,'Synthetic ML author');await page.getByLabel('Governance action reason').fill('Freeze synthetic development observations, supervised training is not justified');await page.getByRole('button',{name:'Freeze development dataset'}).click();await expect(page.getByText('SUPERVISED_TRAINING_NOT_JUSTIFIED',{exact:true}).first()).toBeVisible();
 const registered=page.waitForResponse(r=>r.url().endsWith('/api/intelligence/training-runs')&&r.request().method()==='POST');await page.getByRole('button',{name:'Register statistical candidate'}).first().click();const candidate=await (await registered).json();const artifact=()=>page.getByRole('heading',{name:candidate.model_version,exact:true}).locator('..');await expect(artifact()).toBeVisible();await expect(page.getByText('Statistical candidate registered. It has not been activated.',{exact:true})).toBeVisible();await expect(artifact().getByRole('button',{name:'Evaluate candidate'})).toBeVisible();await artifact().getByRole('button',{name:'Evaluate candidate'}).click();await expect(page.getByText('Actual dataset pipeline diagnostics recorded.',{exact:true})).toBeVisible();await useIdentity(page,'Synthetic ML governor');await page.getByLabel('Governance action reason').fill('Independent approval for synthetic development shadow observation');await artifact().getByRole('button',{name:'Approve development candidate'}).click();
 await expect(page.getByText('Independent development approval recorded. Shadow observations are required before activation.',{exact:true})).toBeVisible();await expect(page.getByLabel('Approved statistical artifact').locator('option[value="'+candidate.model_id+'"]')).toHaveCount(1);await page.getByLabel('Approved statistical artifact').selectOption(candidate.model_id);await page.getByRole('button',{name:'Start shadow observation'}).click();await expect(page.getByRole('heading',{name:'Current deployment'}).locator('..').locator('p > strong').first()).toHaveText('SHADOW');const shadow=(await (await page.request.get('/api/intelligence/registry')).json()).deployment;
 await useIdentity(page,ordinary);await page.goto('/cases/'+id);await expect(page.locator('.page-title .badge')).toHaveText('HOLD',{timeout:30000});await page.getByLabel('Control action reason').fill('Request independently configured authority for the unusual fictional invoice');const requested=page.waitForResponse(r=>r.url().endsWith('/approval-requests')&&r.request().method()==='POST');await page.getByRole('button',{name:'Request current approvals'}).click();expect((await requested).ok()).toBe(true);await expect(page.getByRole('button',{name:'Approve step 1 · MANAGER'})).toBeVisible();
 await useIdentity(page,'Synthetic manager');await page.getByLabel('Control action reason').fill('Manager verifies the fictional obligation');const managerAction=page.waitForResponse(r=>r.url().endsWith('/actions')&&r.request().method()==='POST');await page.getByRole('button',{name:'Approve step 1 · MANAGER'}).click();expect((await managerAction).ok()).toBe(true);await useIdentity(page,'Synthetic department head');await page.getByLabel('Control action reason').fill('Department head verifies the fictional obligation');await page.getByRole('button',{name:'Approve step 2 · DEPARTMENT_HEAD'}).click();await expect(page.locator('.page-title .badge')).toHaveText('PASS',{timeout:30000});await expect(page.getByRole('region',{name:'Transaction intelligence'})).toContainText('Shadow observation');
 await useIdentity(page,'Synthetic ML governor');await page.goto('/intelligence');await page.getByLabel('Governance action reason').fill('Enable transparent anomaly review after observed shadow scores');await page.getByLabel('Approved statistical artifact').selectOption(shadow.model_id);await page.getByRole('button',{name:'Activate anomaly review'}).click();await expect(page.getByRole('heading',{name:'Current deployment'}).locator('..').locator('p > strong').first()).toHaveText('RULES_PLUS_ANOMALY');
 await expect(page.locator('aside .mode strong')).toHaveText('RULES_PLUS_ANOMALY');await expect(page.locator('aside .mode')).toContainText('AVAILABLE');await useIdentity(page,ordinary);await page.goto('/cases/'+id);await page.getByRole('button',{name:'Evaluate current version'}).click();await expect(page.locator('.page-title .badge')).toHaveText('REVIEW',{timeout:30000});await expect(page.getByRole('region',{name:'Transaction intelligence'})).toContainText('Unusual transaction history');await expect(page.getByRole('region',{name:'Transaction intelligence'})).toContainText('91.21');await page.screenshot({path:'../../output/playwright/phase5-anomaly-review.png',fullPage:true});
 await useIdentity(page,'Synthetic ML governor');await page.goto('/intelligence');await page.getByLabel('Governance action reason').fill('Rollback to recorded shadow mode without rewriting scores');await page.getByRole('button',{name:`Rollback to version ${shadow.version} · SHADOW`}).click();await expect(page.getByRole('heading',{name:'Current deployment'}).locator('..').locator('p > strong').first()).toHaveText('SHADOW');await page.getByRole('button',{name:'Use rules only'}).click();await expect(page.getByRole('heading',{name:'Current deployment'}).locator('..').locator('p > strong').first()).toHaveText('RULES_ONLY');await expect(page.locator('aside .mode strong')).toHaveText('RULES_ONLY');await expect(page.locator('aside .mode')).toContainText('NOT_CONFIGURED');await page.screenshot({path:'../../output/playwright/phase5-registry-rollback.png',fullPage:true});
});

test('required model outage is explicit and cannot masquerade as clean risk',async({page})=>{
 const ordinary=(await (await page.request.get('/api/me')).json()).label;await page.goto('/intelligence');await useIdentity(page,'Synthetic ML governor');const current=(await (await page.request.get('/api/intelligence/registry')).json()).deployment;
 await post(page.request,'intelligence/deployments',{expected_version:current.version,mode:'RULES_PLUS_MODEL',reason:'Exercise actual required-model unavailable behavior',threshold:'60.0'});
 try{await useIdentity(page,ordinary);await page.goto('/create');await page.getByLabel('Invoice number',{exact:true}).fill('P5-OUTAGE-'+randomUUID());await page.getByRole('button',{name:'Create and evaluate'}).click();const region=page.getByRole('region',{name:'Transaction intelligence'});await expect(region).toContainText('model unavailable',{timeout:30000});await expect(region).toContainText('Unavailable');await expect(page.locator('.page-title .badge')).toHaveText('HOLD');await page.screenshot({path:'../../output/playwright/phase5-required-outage.png',fullPage:true});}
 finally{await page.goto('/intelligence');await useIdentity(page,'Synthetic ML governor');const active=(await (await page.request.get('/api/intelligence/registry')).json()).deployment;await post(page.request,'intelligence/deployments',{expected_version:active.version,mode:'RULES_ONLY',reason:'Restore explicit compatibility mode after outage verification',threshold:'60.0'})}
});

test('intelligence loading failure and governance empty states are accessible',async({page})=>{
 const ordinary=(await (await page.request.get('/api/me')).json()).label;const records=(await (await page.request.get('/api/transactions?limit=200')).json()).items;const record=records.find((r:{latest_evaluation_id:string|null})=>r.latest_evaluation_id);
 await page.route('**/api/evaluations/*/intelligence',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Retained intelligence temporarily unavailable'}})}));await page.goto('/cases/'+record.id);await expect(page.getByRole('region',{name:'Transaction intelligence'}).getByRole('alert')).toContainText('temporarily unavailable');await page.unroute('**/api/evaluations/*/intelligence');await page.getByRole('button',{name:'Refresh intelligence'}).click();await expect(page.getByRole('region',{name:'Transaction intelligence'}).getByRole('alert')).toHaveCount(0);
 await page.goto('/intelligence');await useIdentity(page,'Synthetic ML author');await page.route('**/api/intelligence/registry',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({deployment:{version:0,mode:'RULES_ONLY',model_id:null},models:[],datasets:[],deployments:[]})}));await page.reload();await expect(page.getByText('No registered artifacts. Candidate creation and activation are separate actions.')).toBeVisible();await expect(page.getByText('No frozen datasets. Collect source-linked adjudication before creating a manifest.')).toBeVisible();await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement?.tagName)).not.toBe('BODY');await page.screenshot({path:'../../output/playwright/phase5-empty-registry.png',fullPage:true});await page.unroute('**/api/intelligence/registry');await useIdentity(page,ordinary);
});
