import {test,expect,type APIRequestContext} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
const origin='http://127.0.0.1:3000';
async function post(request:APIRequestContext,path:string,data:unknown){const r=await request.post('/api/'+path,{headers:{Origin:origin,'Idempotency-Key':randomUUID()},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json()}
const source=(kind:string)=>JSON.parse(readFileSync(resolve('../../data/synthetic/reference/'+kind+'.json'),'utf8')).records;
async function invoice(request:APIRequestContext){
 const p=await (await request.get('/api/development/templates/vendor')).json();p.invoice_number='SYNTHETIC-P4-'+randomUUID();
 const budget=structuredClone(source('budgets')[0]),po=structuredClone(source('purchase_orders')[0]),line=structuredClone(po.lines[0]),grn=structuredClone(source('goods_receipts')[0].lines[0]),doc=structuredClone(source('documents').find((d:{id:string})=>d.id===p.source_document_id));
 budget.id=randomUUID();budget.ledger=[{id:randomUUID(),entry_type:'ALLOCATION',amount:'1000000.00',currency:'INR'}];po.id=randomUUID();po.budget_id=budget.id;po.approved_ceiling_amount='1000000.00';delete po.lines;line.id=randomUUID();line.po_id=po.id;line.ordered_quantity='100';grn.id=randomUUID();grn.po_id=po.id;grn.po_line_id=line.id;grn.accepted_quantity='100';grn.returned_quantity='0';grn.reversed_quantity='0';doc.id=randomUUID();doc.facts.invoice_number=p.invoice_number;
 p.budget_id=budget.id;p.po_id=po.id;p.lines[0].po_line_id=line.id;p.lines[0].grn_line_id=grn.id;p.source_document_id=doc.id;
 const batch=await post(request,'reference-imports',{source_system:'SYNTHETIC_PHASE4_BROWSER',source_version:randomUUID(),reason:'Independent fictional review workflow evidence',records:[{kind:'budgets',payload:budget},{kind:'purchase_orders',payload:po},{kind:'po_lines',payload:line},{kind:'grn_lines',payload:grn},{kind:'documents',payload:doc}]});
 expect((await post(request,'reference-imports/'+batch.id+'/validate',{})).state).toBe('VALID');await post(request,'reference-imports/'+batch.id+'/activate',{reason:'Activate independently validated fictional evidence'});
 const c=await post(request,'transactions',p);await post(request,'transactions/'+c.id+'/evaluate',{expected_version:1,reason:'Screen the fictional Phase-4 review case'});return {id:c.id,p}
}

test('claim inspect evidence stale action correction and timeline use the live backend',async({page,context})=>{
 const {id,p}=await invoice(page.request);await page.goto('/cases/'+id);await expect(page.locator('.page-title .badge')).toHaveText('HOLD',{timeout:30000});
 await page.getByRole('button',{name:'Claim case',exact:true}).click();await expect(page.getByRole('region',{name:'Review workflow'})).toContainText('Review version 2');
 await page.getByText('View detailed checks',{exact:true}).click();await page.locator('.rule').first().getByText('Observed, expected & evidence').click();await page.locator('.rule').first().getByRole('button',{name:/TRANSACTION/}).click();await expect(page.getByRole('heading',{name:'Resolved evidence'})).toBeVisible();
 const second=await context.newPage();await second.goto('/cases/'+id);await expect(second.getByLabel('Review reason')).toBeVisible();await second.getByLabel('Review reason').fill('Ask for the independently required finance approval');await second.getByLabel('Requested evidence or information').fill('Provide the authorized approval chain');await second.getByRole('button',{name:'Request information',exact:true}).click();await expect(second.getByRole('region',{name:'Review workflow'})).toContainText('awaiting information');
 await page.getByLabel('Review reason').fill('Stale review must be rejected');await page.getByLabel('Requested evidence or information').fill('Submit stale information request');await page.getByRole('button',{name:'Request information',exact:true}).click();await expect(page.getByRole('region',{name:'Review workflow'}).getByRole('alert')).toContainText('changed after you opened it');
 await page.getByRole('button',{name:'Refresh review',exact:true}).click();await page.getByText('Correct a canonical or source field',{exact:true}).click();await page.getByLabel('Field to correct').selectOption('invoice_number');await page.getByLabel('Corrected value',{exact:true}).fill(p.invoice_number+'-REV');await page.getByRole('button',{name:'Save field correction'}).click();await expect(page.getByRole('heading',{name:p.invoice_number+'-REV',exact:true})).toBeVisible();await expect(page.locator('.page-title')).toContainText('VERSION 2');await expect(page.locator('.page-title .badge')).toHaveText('HOLD',{timeout:30000});
 await page.getByRole('button',{name:'Refresh timeline'}).click();await expect(page.getByRole('region',{name:'Audit timeline'})).toContainText('review correct field');await expect(page.getByRole('region',{name:'Audit timeline'})).toContainText('eligibility invalidated');await page.screenshot({path:'../../output/playwright/phase4-correction-timeline.png',fullPage:true});await second.close();
});

test('resolution keeps the original report and export uses separate auditor authority',async({page})=>{
 const label=(await (await page.request.get('/api/me')).json()).label;const {id}=await invoice(page.request);await page.goto('/cases/'+id);await expect(page.locator('.page-title .badge')).toHaveText('HOLD',{timeout:30000});const old=(await (await page.request.get('/api/transactions/'+id)).json()).latest_evaluation_id;
 await page.getByRole('button',{name:'Claim case',exact:true}).click();await page.getByLabel('Control action reason').fill('Request the actual configured authority chain');await page.getByRole('button',{name:'Request current approvals'}).click();await expect(page.getByText('Request for v1',{exact:false})).toBeVisible();
 await page.getByLabel('Configured demo identity').selectOption('Synthetic manager');await page.getByLabel('Control action reason').fill('Manager approves the verified fictional obligation');await page.getByRole('button',{name:'Approve step 1 · MANAGER'}).click();
 await page.getByLabel('Configured demo identity').selectOption('Synthetic department head');await page.getByLabel('Control action reason').fill('Department head approves the verified fictional obligation');await page.getByRole('button',{name:'Approve step 2 · DEPARTMENT_HEAD'}).click();await expect(page.locator('.page-title .badge')).toHaveText('PASS',{timeout:30000});
 await page.getByLabel('Configured demo identity').selectOption(label);await page.getByLabel('Review reason').fill('All required controls resolved by a fresh evaluation');await page.getByRole('button',{name:'Resolve exception'}).click();await expect(page.getByRole('region',{name:'Review workflow'})).toContainText('resolved');
 await page.goto('/reports/'+old);await expect(page.getByText('Evaluation status: SUPERSEDED')).toBeVisible();await expect(page.locator('.notice .badge')).toHaveText('HOLD');await expect(page.getByText('Report downloads require explicit export permission.')).toBeVisible();
 await page.getByLabel('Configured demo identity').selectOption('Synthetic auditor');const downloading=page.waitForEvent('download');await page.getByRole('link',{name:'Download CSV'}).click();const download=await downloading;expect(download.suggestedFilename()).toMatch(/\.csv$/);await expect(page.getByRole('link',{name:'Download JSON'})).toBeVisible();await page.screenshot({path:'../../output/playwright/phase4-retained-report.png',fullPage:true});
});

test('terminal corrupt document is visible to operations and cannot be manually retried',async({page})=>{
 const upload=await post(page.request,'uploads',{filename:'synthetic-corrupt-phase4.pdf',mime:'application/pdf',source_type:'VENDOR_INVOICE'});const bytes=await page.request.post('/api/uploads/'+upload.id+'/bytes',{headers:{Origin:origin,'Content-Type':'application/octet-stream'},data:Buffer.from('%PDF-1.7\nInvalid synthetic PDF structure\n%%EOF')});expect(bytes.ok(),await bytes.text()).toBeTruthy();await post(page.request,'uploads/'+upload.id+'/finalize',{});
 await expect.poll(async()=> (await (await page.request.get('/api/documents/'+upload.document_id)).json()).state,{timeout:30000}).toBe('QUARANTINED');
 await page.goto('/operations');await page.getByLabel('Configured demo identity').selectOption('Synthetic operations administrator');await expect(page.getByRole('heading',{name:'Processing failures',exact:true})).toBeVisible();const row=page.getByRole('row').filter({has:page.getByRole('link',{name:'Document '+upload.document_id.slice(-8)})});await expect(row).toContainText('CORRUPT_DOCUMENT');await expect(row.getByRole('button',{name:'Retry job'})).toHaveCount(0);await row.getByText('Failure details').click();await expect(row).toContainText('First failure:');
 await page.getByLabel('Recovery reason').fill('Inspect retained failure and scoped operational consistency');await page.getByRole('button',{name:'Run reconciliation'}).click();await expect(page.getByRole('heading',{name:'Dependencies'})).toBeVisible();await expect(page.getByText('DEFERRED_EXTERNAL_PREREQUISITE',{exact:true})).toBeVisible();await page.screenshot({path:'../../output/playwright/phase4-dead-letter.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('queue filters pagination keyboard focus empty and operational error states',async({page})=>{
 await page.goto('/queue');await page.getByLabel('Owner',{exact:true}).selectOption('unassigned');await page.getByLabel('Review state',{exact:true}).selectOption('OPEN');await page.goto('/queue?reason=NO_SUCH_RULE');await expect(page.getByText('No open exceptions match')).toBeVisible();await page.getByLabel('Reason',{exact:true}).selectOption('APR-001');await expect(page.getByRole('columnheader',{name:'Owner / state'})).toBeVisible();await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement?.tagName)).not.toBe('BODY');
 await page.getByLabel('Configured demo identity').selectOption('Synthetic operations administrator');await page.route('**/api/operations/dashboard',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Operational measurements temporarily unavailable'}})}));await page.goto('/operations');await expect(page.getByRole('alert').filter({hasText:'Operational measurements temporarily unavailable'})).toBeVisible();await page.unroute('**/api/operations/dashboard');await page.reload();await expect(page.getByRole('heading',{name:'Review workload'})).toBeVisible();await page.screenshot({path:'../../output/playwright/phase4-operations.png',fullPage:true});
});
