"""establish Phase 1 vertical slice

Revision ID: 0001_phase1
Revises:
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '0001_phase1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('audit_sequence', sa.BigInteger(), nullable=False),
    sa.Column('audit_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_table('audit_events',
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('object_version', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'sequence')
    )
    op.create_index('ix_audit_scope_object', 'audit_events', ['tenant_id', 'legal_entity_id', 'object_id', 'sequence'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.String(length=160), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'actor_id', 'endpoint', 'key'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('import_batches',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=160), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('object_key', sa.String(length=200), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('PREVIEWED','COMMITTED')"),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('reference_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('party_id', sa.Uuid(), nullable=True),
    sa.Column('number_key', sa.String(length=160), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('version > 0'),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id', 'version'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id', 'version')
    )
    op.create_index('ix_history_exact', 'reference_records', ['tenant_id', 'legal_entity_id', 'kind', 'party_id', 'number_key', 'currency', 'amount', 'business_date'], unique=False)
    op.create_index('ix_reference_kind_scope', 'reference_records', ['tenant_id', 'legal_entity_id', 'kind'], unique=False)
    op.create_table('reference_snapshots',
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'content_digest'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('transactions',
    sa.Column('branch', sa.String(length=32), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('processing_state', sa.String(length=32), nullable=False),
    sa.Column('latest_evaluation_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.String(length=8), nullable=True),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("NOT eligible OR (decision IS NOT NULL AND decision = 'PASS' AND processing_state = 'COMPLETED')"),
    sa.CheckConstraint("branch IN ('VENDOR_INVOICE','EMPLOYEE_EXPENSE')"),
    sa.CheckConstraint("decision IS NULL OR decision IN ('PASS','REVIEW','HOLD')"),
    sa.CheckConstraint('latest_version > 0 AND row_version > 0'),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_index('ix_transaction_scope_created', 'transactions', ['tenant_id', 'legal_entity_id', 'created_at', 'id'], unique=False)
    op.create_table('import_rows',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('sheet', sa.String(length=160), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('row_digest', sa.String(length=64), nullable=False),
    sa.Column('canonical_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('validation_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('row_number > 0'),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'batch_id'], ['import_batches.tenant_id', 'import_batches.legal_entity_id', 'import_batches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'transaction_id'], ['transactions.tenant_id', 'transactions.legal_entity_id', 'transactions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'batch_id', 'sheet', 'row_number'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('reference_links',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('child_version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('parent_version', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=48), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'child_id', 'child_version'], ['reference_records.tenant_id', 'reference_records.legal_entity_id', 'reference_records.id', 'reference_records.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'parent_id', 'parent_version'], ['reference_records.tenant_id', 'reference_records.legal_entity_id', 'reference_records.id', 'reference_records.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'child_id', 'child_version', 'parent_id', 'parent_version', 'relationship'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('snapshot_members',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'record_id', 'record_version'], ['reference_records.tenant_id', 'reference_records.legal_entity_id', 'reference_records.id', 'reference_records.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'snapshot_id'], ['reference_snapshots.tenant_id', 'reference_snapshots.legal_entity_id', 'reference_snapshots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'snapshot_id', 'record_id', 'record_version')
    )
    op.create_table('transaction_versions',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('normalizer_version', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('party_id', sa.Uuid(), nullable=True),
    sa.Column('number_key', sa.String(length=160), nullable=True),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version > 0'),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'transaction_id'], ['transactions.tenant_id', 'transactions.legal_entity_id', 'transactions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'transaction_id', 'version')
    )
    op.create_index('ix_transaction_exact', 'transaction_versions', ['tenant_id', 'legal_entity_id', 'party_id', 'number_key', 'currency', 'total_amount', 'business_date'], unique=False)
    op.create_table('approval_records',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_version', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence > 0'),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'policy_id', 'policy_version'], ['reference_records.tenant_id', 'reference_records.legal_entity_id', 'reference_records.id', 'reference_records.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'transaction_id', 'transaction_version'], ['transaction_versions.tenant_id', 'transaction_versions.legal_entity_id', 'transaction_versions.transaction_id', 'transaction_versions.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('evaluations',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_version', sa.Integer(), nullable=False),
    sa.Column('reference_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=32), nullable=False),
    sa.Column('decision_policy_version', sa.String(length=32), nullable=False),
    sa.Column('evaluation_mode', sa.String(length=32), nullable=False),
    sa.Column('completeness', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('input_digest', sa.String(length=64), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("NOT eligible OR (decision = 'PASS' AND completeness = 'COMPLETE')"),
    sa.CheckConstraint("completeness IN ('COMPLETE','INCOMPLETE')"),
    sa.CheckConstraint("decision IN ('PASS','REVIEW','HOLD')"),
    sa.CheckConstraint("evaluation_mode = 'RULES_ONLY'"),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'reference_snapshot_id'], ['reference_snapshots.tenant_id', 'reference_snapshots.legal_entity_id', 'reference_snapshots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'supersedes_id'], ['evaluations.tenant_id', 'evaluations.legal_entity_id', 'evaluations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'transaction_id', 'transaction_version'], ['transaction_versions.tenant_id', 'transaction_versions.legal_entity_id', 'transaction_versions.transaction_id', 'transaction_versions.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('capacity_reservations',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_version', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('reference_version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('BUDGET','PO_LINE','GRN_LINE')"),
    sa.CheckConstraint("state IN ('ACTIVE','RELEASED')"),
    sa.CheckConstraint('amount >= 0 AND quantity >= 0'),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'evaluation_id'], ['evaluations.tenant_id', 'evaluations.legal_entity_id', 'evaluations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'reference_id', 'reference_version'], ['reference_records.tenant_id', 'reference_records.legal_entity_id', 'reference_records.id', 'reference_records.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'transaction_id'], ['transactions.tenant_id', 'transactions.legal_entity_id', 'transactions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'evaluation_id', 'reference_id', 'kind'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_index('ix_capacity_active', 'capacity_reservations', ['tenant_id', 'legal_entity_id', 'reference_id', 'kind', 'state'], unique=False)
    op.create_table('jobs',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_version', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('stage_version', sa.String(length=32), nullable=False),
    sa.Column('stage_key', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('maximum_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.Uuid(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.String(length=64), nullable=True),
    sa.Column('result_evaluation_id', sa.Uuid(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('QUEUED','RUNNING','RETRYABLE','SUCCEEDED','FAILED','CANCELLED','STALE')"),
    sa.CheckConstraint('attempts >= 0 AND maximum_attempts > 0'),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'result_evaluation_id'], ['evaluations.tenant_id', 'evaluations.legal_entity_id', 'evaluations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'snapshot_id'], ['reference_snapshots.tenant_id', 'reference_snapshots.legal_entity_id', 'reference_snapshots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'transaction_id'], ['transactions.tenant_id', 'transactions.legal_entity_id', 'transactions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'stage_key')
    )
    op.create_index('ix_job_lease', 'jobs', ['tenant_id', 'legal_entity_id', 'state', 'available_at', 'lease_until'], unique=False)
    op.create_table('reports',
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'evaluation_id'], ['evaluations.tenant_id', 'evaluations.legal_entity_id', 'evaluations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'evaluation_id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('review_cases',
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('branch', sa.String(length=32), nullable=False),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('REVIEW','HOLD')"),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'evaluation_id'], ['evaluations.tenant_id', 'evaluations.legal_entity_id', 'evaluations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'transaction_id'], ['transactions.tenant_id', 'transactions.legal_entity_id', 'transactions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'evaluation_id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_index('ix_review_queue', 'review_cases', ['tenant_id', 'legal_entity_id', 'state', 'decision', 'created_at'], unique=False)
    op.create_table('rule_results',
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('decision_effect', sa.String(length=8), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision_effect IN ('NONE','REVIEW','HOLD')"),
    sa.CheckConstraint("status IN ('PASS','FAIL','UNKNOWN','NOT_APPLICABLE','ERROR')"),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'evaluation_id'], ['evaluations.tenant_id', 'evaluations.legal_entity_id', 'evaluations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'evaluation_id', 'rule_id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('evidence_objects',
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('rule_result_id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'evaluation_id'], ['evaluations.tenant_id', 'evaluations.legal_entity_id', 'evaluations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'rule_result_id'], ['rule_results.tenant_id', 'rule_results.legal_entity_id', 'rule_results.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('outbox_events',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('schema_version', sa.String(length=24), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'job_id'], ['jobs.tenant_id', 'jobs.legal_entity_id', 'jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'job_id', 'event_type')
    )
    # ### end Alembic commands ###

    # Freeze the initial schema security contract in this migration.
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("CREATE FUNCTION reject_fact_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'immutable financial fact'; END $$")
        op.execute("ALTER TABLE tenants ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE tenants FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON tenants USING (id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (id = nullif(current_setting('app.tenant_id', true), '')::uuid)")
        op.execute("ALTER TABLE legal_entities ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE legal_entities FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON legal_entities USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)")
        op.execute("ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE audit_events FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON audit_events USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE idempotency_records ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE idempotency_records FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON idempotency_records USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE import_batches ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE import_batches FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON import_batches USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE reference_records ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE reference_records FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON reference_records USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE reference_snapshots ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE reference_snapshots FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON reference_snapshots USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE transactions ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE transactions FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON transactions USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE import_rows ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE import_rows FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON import_rows USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE reference_links ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE reference_links FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON reference_links USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE snapshot_members ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE snapshot_members FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON snapshot_members USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE transaction_versions ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE transaction_versions FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON transaction_versions USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE approval_records ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE approval_records FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON approval_records USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE evaluations ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE evaluations FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON evaluations USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE capacity_reservations ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE capacity_reservations FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON capacity_reservations USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE jobs ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE jobs FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON jobs USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE reports ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE reports FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON reports USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE review_cases ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE review_cases FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON review_cases USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE rule_results ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE rule_results FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON rule_results USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE evidence_objects ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE evidence_objects FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON evidence_objects USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("ALTER TABLE outbox_events ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE outbox_events FORCE ROW LEVEL SECURITY")
        op.execute("CREATE POLICY scope_isolation ON outbox_events USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
        op.execute("CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON reference_records FOR EACH ROW EXECUTE FUNCTION reject_fact_mutation()")
        op.execute("CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON reference_links FOR EACH ROW EXECUTE FUNCTION reject_fact_mutation()")
        op.execute("CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON reference_snapshots FOR EACH ROW EXECUTE FUNCTION reject_fact_mutation()")
        op.execute("CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON snapshot_members FOR EACH ROW EXECUTE FUNCTION reject_fact_mutation()")
        op.execute("CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON transaction_versions FOR EACH ROW EXECUTE FUNCTION reject_fact_mutation()")
        op.execute("CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON approval_records FOR EACH ROW EXECUTE FUNCTION reject_fact_mutation()")
        op.execute("CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON evaluations FOR EACH ROW EXECUTE FUNCTION reject_fact_mutation()")
        op.execute("CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON rule_results FOR EACH ROW EXECUTE FUNCTION reject_fact_mutation()")
        op.execute("CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON evidence_objects FOR EACH ROW EXECUTE FUNCTION reject_fact_mutation()")
        op.execute("CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON reports FOR EACH ROW EXECUTE FUNCTION reject_fact_mutation()")
        op.execute("CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION reject_fact_mutation()")
        op.execute("CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON idempotency_records FOR EACH ROW EXECUTE FUNCTION reject_fact_mutation()")
        op.execute("CREATE FUNCTION protect_import_source() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF (NEW.batch_id, NEW.sheet, NEW.row_number, NEW.raw_values, NEW.row_digest, NEW.canonical_payload, NEW.validation_errors, NEW.tenant_id, NEW.legal_entity_id) IS DISTINCT FROM (OLD.batch_id, OLD.sheet, OLD.row_number, OLD.raw_values, OLD.row_digest, OLD.canonical_payload, OLD.validation_errors, OLD.tenant_id, OLD.legal_entity_id) THEN RAISE EXCEPTION 'immutable import source'; END IF; RETURN NEW; END $$")
        op.execute("CREATE TRIGGER immutable_import_source BEFORE UPDATE ON import_rows FOR EACH ROW EXECUTE FUNCTION protect_import_source()")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbox_events')
    op.drop_table('evidence_objects')
    op.drop_table('rule_results')
    op.drop_index('ix_review_queue', table_name='review_cases')
    op.drop_table('review_cases')
    op.drop_table('reports')
    op.drop_index('ix_job_lease', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_capacity_active', table_name='capacity_reservations')
    op.drop_table('capacity_reservations')
    op.drop_table('evaluations')
    op.drop_table('approval_records')
    op.drop_index('ix_transaction_exact', table_name='transaction_versions')
    op.drop_table('transaction_versions')
    op.drop_table('snapshot_members')
    op.drop_table('reference_links')
    op.drop_table('import_rows')
    op.drop_index('ix_transaction_scope_created', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('reference_snapshots')
    op.drop_index('ix_reference_kind_scope', table_name='reference_records')
    op.drop_index('ix_history_exact', table_name='reference_records')
    op.drop_table('reference_records')
    op.drop_table('import_batches')
    op.drop_table('idempotency_records')
    op.drop_index('ix_audit_scope_object', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('legal_entities')
    op.drop_table('tenants')
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == 'postgresql':
        op.execute("DROP FUNCTION protect_import_source()")
        op.execute("DROP FUNCTION reject_fact_mutation()")
