"""Add immutable scoped document pipeline and sources

Revision ID: 0004_documents
Revises: 0003_generation
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '0004_documents'
down_revision = '0003_generation'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.String(length=64), nullable=True),
    sa.Column('last_successful_stage', sa.String(length=32), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('segmentation_state', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type IN ('VENDOR_INVOICE','EMPLOYEE_RECEIPT','SUPPORTING_DOCUMENT')"),
    sa.CheckConstraint("state IN ('AWAITING_UPLOAD','UPLOADED','QUEUED','PROCESSING','QUARANTINED','NEEDS_INPUT','DEPENDENCY_UNAVAILABLE','FAILED_RETRYABLE','FAILED_FINAL','READY')"),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('upload_sessions',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('declared_mime', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_key', sa.String(length=128), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('OPEN','UPLOADED','FINALIZED','QUARANTINED','EXPIRED')"),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'document_id'], ['documents.tenant_id', 'documents.legal_entity_id', 'documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=128), nullable=False),
    sa.Column('storage_version', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('detected_mime', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('version > 0 AND byte_size > 0'),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'id'], ['documents.tenant_id', 'documents.legal_entity_id', 'documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'upload_id'], ['upload_sessions.tenant_id', 'upload_sessions.legal_entity_id', 'upload_sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id', 'version'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id', 'version'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'upload_id')
    )
    op.create_table('import_cells',
    sa.Column('row_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('sheet', sa.String(length=160), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('column', sa.String(length=160), nullable=False),
    sa.Column('field_path', sa.String(length=160), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('parsed_value', sa.Text(), nullable=True),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('row_number > 0'),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'batch_id'], ['import_batches.tenant_id', 'import_batches.legal_entity_id', 'import_batches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'row_id'], ['import_rows.tenant_id', 'import_rows.legal_entity_id', 'import_rows.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'row_id', 'column', 'field_path')
    )
    op.create_table('document_jobs',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('stage_version', sa.String(length=32), nullable=False),
    sa.Column('stage_key', sa.String(length=64), nullable=False),
    sa.Column('result_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('maximum_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.Uuid(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('last_error', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("stage IN ('PREPROCESS','EXTRACT','NORMALIZE','VALIDATE','FINALIZE')"),
    sa.CheckConstraint("state IN ('QUEUED','RUNNING','RETRYABLE','SUCCEEDED','FAILED','STALE')"),
    sa.CheckConstraint('attempts >= 0 AND maximum_attempts > 0'),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'document_id', 'document_version'], ['document_versions.tenant_id', 'document_versions.legal_entity_id', 'document_versions.id', 'document_versions.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'stage_key')
    )
    op.create_table('document_pages',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('processor_version', sa.String(length=32), nullable=False),
    sa.Column('preview_key', sa.String(length=128), nullable=False),
    sa.Column('page_sha256', sa.String(length=64), nullable=False),
    sa.Column('native_text', sa.Text(), nullable=False),
    sa.Column('spans', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('transform', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('quality', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('route', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('page >= 1 AND page <= 30'),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'document_id', 'document_version'], ['document_versions.tenant_id', 'document_versions.legal_entity_id', 'document_versions.id', 'document_versions.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'document_id', 'document_version', 'processor_version', 'page'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('source_corrections',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_version', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'document_id', 'document_version'], ['document_versions.tenant_id', 'document_versions.legal_entity_id', 'document_versions.id', 'document_versions.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'transaction_id', 'transaction_version'], ['transaction_versions.tenant_id', 'transaction_versions.legal_entity_id', 'transaction_versions.transaction_id', 'transaction_versions.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('document_outbox',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'job_id'], ['document_jobs.tenant_id', 'document_jobs.legal_entity_id', 'document_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'job_id')
    )
    op.create_table('extraction_runs',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('adapter', sa.String(length=80), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'document_id', 'document_version'], ['document_versions.tenant_id', 'document_versions.legal_entity_id', 'document_versions.id', 'document_versions.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'job_id'], ['document_jobs.tenant_id', 'document_jobs.legal_entity_id', 'document_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'job_id', 'attempt')
    )
    op.create_table('document_drafts',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=False),
    sa.Column('normalizer_version', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('candidate', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('traces', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'document_id', 'document_version'], ['document_versions.tenant_id', 'document_versions.legal_entity_id', 'document_versions.id', 'document_versions.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'extraction_run_id'], ['extraction_runs.tenant_id', 'extraction_runs.legal_entity_id', 'extraction_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'extraction_run_id', 'stage', 'normalizer_version'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('field_observations',
    sa.Column('extraction_run_id', sa.Uuid(), nullable=False),
    sa.Column('field_path', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('parsed_candidate', sa.Text(), nullable=True),
    sa.Column('source', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('diagnostic', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('PRESENT','MISSING','ILLEGIBLE','AMBIGUOUS','NOT_APPLICABLE')"),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'extraction_run_id'], ['extraction_runs.tenant_id', 'extraction_runs.legal_entity_id', 'extraction_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'extraction_run_id', 'field_path'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id')
    )
    op.create_table('transaction_documents',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_version', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('first_page', sa.Integer(), nullable=False),
    sa.Column('last_page', sa.Integer(), nullable=False),
    sa.Column('verification_id', sa.Uuid(), nullable=True),
    sa.Column('verification_version', sa.Integer(), nullable=True),
    sa.Column('draft_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('INVOICE','RECEIPT','PO','SUPPORT')"),
    sa.CheckConstraint('first_page >= 1 AND last_page >= first_page AND last_page <= 30'),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'document_id', 'document_version'], ['document_versions.tenant_id', 'document_versions.legal_entity_id', 'document_versions.id', 'document_versions.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'draft_id'], ['document_drafts.tenant_id', 'document_drafts.legal_entity_id', 'document_drafts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'transaction_id', 'transaction_version'], ['transaction_versions.tenant_id', 'transaction_versions.legal_entity_id', 'transaction_versions.transaction_id', 'transaction_versions.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id', 'verification_id', 'verification_version'], ['reference_records.tenant_id', 'reference_records.legal_entity_id', 'reference_records.id', 'reference_records.version'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'legal_entity_id'], ['legal_entities.tenant_id', 'legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'legal_entity_id', 'transaction_id', 'transaction_version', 'document_id')
    )
    for table in ('documents','upload_sessions','document_versions','import_cells','document_jobs','document_pages','source_corrections','document_outbox','extraction_runs','document_drafts','field_observations','transaction_documents'):
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY')
        op.execute(f"CREATE POLICY scope_isolation ON {table} USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid) WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND legal_entity_id = nullif(current_setting('app.legal_entity_id', true), '')::uuid)")
    for table in ('document_versions','import_cells','document_pages','source_corrections','extraction_runs','document_drafts','field_observations','transaction_documents'):
        op.execute(f'CREATE TRIGGER immutable_fact BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION reject_fact_mutation()')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_documents')
    op.drop_table('field_observations')
    op.drop_table('document_drafts')
    op.drop_table('extraction_runs')
    op.drop_table('document_outbox')
    op.drop_table('source_corrections')
    op.drop_table('document_pages')
    op.drop_table('document_jobs')
    op.drop_table('import_cells')
    op.drop_table('document_versions')
    op.drop_table('upload_sessions')
    op.drop_table('documents')
    # ### end Alembic commands ###
