export const screeningLabel=(value:string|null)=>({PASS:'Ready for processing',REVIEW:'Needs review',HOLD:'On hold'}[value||'']||'Awaiting screening');
export const processingLabel=(value:string)=>({READY:'Ready to verify',NEEDS_INPUT:'Needs your confirmation',QUEUED:'Waiting to process',PROCESSING:'Processing',COMPLETED:'Screening complete',RECEIVED:'Received',FAILED_RETRYABLE:'Retry scheduled',FAILED_FINAL:'Processing stopped',QUARANTINED:'File quarantined',DEPENDENCY_UNAVAILABLE:'Service unavailable',CANCELLED:'Cancelled'}[value]||value.toLowerCase().replaceAll('_',' '));
export const fieldLabel=(field:string)=>{
 if(field==='document')return 'Document checks';if(field==='lines')return 'Line items';
 const bits=field.split('.');if(bits[0]==='lines'&&bits.length===2)return `Line ${Number(bits[1])+1} checks`;const name=bits.at(-1)!;
 const label:Record<string,string>={vendor_name:'Supplier name',merchant_name:'Merchant',invoice_number:'Invoice number',invoice_date:'Invoice date',due_date:'Due date',po_reference:'Purchase order',subtotal_amount:'Subtotal',tax_amount:'Tax amount',total_amount:'Total',tax_basis:'Tax treatment',document_discount_amount:'Document discount',shipping_amount:'Shipping',other_charges_amount:'Other charges',quantity:'Quantity',description:'Description',unit_price:'Unit price',net_amount:'Net amount',gross_amount:'Gross amount',amount:'Printed line amount',tax_rate:'Tax rate',uom:'Unit of measure',bill_to_address:'Billing address',ship_to_address:'Delivery address',customer_bill_to:'Bill-to customer',vendor_address:'Supplier address',local_timezone:'Local timezone'};
 return (bits[0]==='lines'?`Line ${Number(bits[1])+1}: `:'')+(label[name]||name.replaceAll('_',' '));
};
export const observationLabel=(state:string)=>({PRESENT:'Extracted · confirm against source',MISSING:'Missing',AMBIGUOUS:'Ambiguous',ILLEGIBLE:'Illegible',NOT_APPLICABLE:'Printed as not applicable'}[state]||state);
export function workspaceIdentity(label:string){return label.replace(/^Synthetic\s+/i,'').replace(/^Hackathon\s+/i,'').replace(/^./,x=>x.toUpperCase());}
